repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black

- repo: https://github.com/flakeheaven/flakeheaven
  rev: 3.3.0
  hooks:
  - id: flakeheaven
    args: [lint]

- repo: local
  hooks:
  - id: run_tests
    language: script
    name: Run tests
    entry: ./scripts/run_tests.sh
