"""Feed Item."""
# Do not Edit this file.
# This file is generated from the "gitgus dev generate-sobjects" command
#
# Remember, you can always regenerate this file by running the above command.
# If you have made changes to this file, they will be lost.
# Edit template: sobject.py.jinja2

from datetime import datetime
from enum import Enum
from typing import Any
from typing import Self
from typing import Dict
from typing import List
from typing import Optional
from typing import Generator

from pydantic import Field, ConfigDict, computed_field
from ..gus_client import GUSClient
from .sobject_base import SObjectBase, SObjectType


class TypeEnum(str, Enum):
    """Feed Item Type."""

    OPTION_0 = "TrackedChange"
    OPTION_1 = "UserStatus"
    OPTION_2 = "TextPost"
    OPTION_3 = "AdvancedTextPost"
    OPTION_4 = "LinkPost"
    OPTION_5 = "ContentPost"
    OPTION_6 = "PollPost"
    OPTION_7 = "RypplePost"
    OPTION_8 = "ProfileSkillPost"
    OPTION_9 = "DashboardComponentSnapshot"
    OPTION_10 = "ApprovalPost"
    OPTION_11 = "CaseCommentPost"
    OPTION_12 = "ReplyPost"
    OPTION_13 = "EmailMessageEvent"
    OPTION_14 = "CallLogPost"
    OPTION_15 = "ChangeStatusPost"
    OPTION_16 = "AttachArticleEvent"
    OPTION_17 = "MilestoneEvent"
    OPTION_18 = "ActivityEvent"
    OPTION_19 = "ChatTranscriptPost"
    OPTION_20 = "CollaborationGroupCreated"
    OPTION_21 = "CollaborationGroupUnarchived"
    OPTION_22 = "SocialPost"
    OPTION_23 = "QuestionPost"
    OPTION_24 = "FacebookPost"
    OPTION_25 = "BasicTemplateFeedItem"
    OPTION_26 = "CreateRecordEvent"
    OPTION_27 = "CanvasPost"
    OPTION_28 = "AnnouncementPost"


class NetworkScopeEnum(str, Enum):
    """Network Scope."""

    OPTION_0 = "AllNetworks"


class VisibilityEnum(str, Enum):
    """Visibility."""

    OPTION_0 = "AllUsers"
    OPTION_1 = "InternalUsers"


class StatusEnum(str, Enum):
    """Status."""

    OPTION_0 = "Published"
    OPTION_1 = "PendingReview"
    OPTION_2 = "Draft"


class FeedItem(SObjectBase, metaclass=SObjectType):
    """Feed Item."""

    _can_be_approved = True
    _base_sf_object = "FeedItem"

    model_config = ConfigDict(
        title="FeedItem",
        validate_assignment=True,
    )

    id_: str = Field(..., alias="Id", title="Feed Item ID", frozen=True, exclude=True)
    parent_id: str = Field(..., alias="ParentId", title="Parent ID", frozen=True, exclude=True)
    type_: Optional[TypeEnum] = Field(..., alias="Type", title="Feed Item Type", frozen=True, exclude=True)
    created_by_id: str = Field(..., alias="CreatedById", title="Created By ID", frozen=True, exclude=True)
    created_date: datetime = Field(..., alias="CreatedDate", title="Created Date", frozen=True, exclude=True)
    is_deleted: bool = Field(..., alias="IsDeleted", title="Deleted", frozen=True, exclude=True)
    last_modified_date: datetime = Field(
        ..., alias="LastModifiedDate", title="Last Modified Date", frozen=True, exclude=True
    )
    system_modstamp: datetime = Field(..., alias="SystemModstamp", title="System Modstamp", frozen=True, exclude=True)
    revision: Optional[int] = Field(..., alias="Revision", title="Revision", frozen=True, exclude=True)
    last_edit_by_id: Optional[str] = Field(
        ..., alias="LastEditById", title="Last Edit By ID", frozen=True, exclude=True
    )
    last_edit_date: Optional[datetime] = Field(
        ..., alias="LastEditDate", title="Last Edit Date", frozen=True, exclude=True
    )
    comment_count: int = Field(..., alias="CommentCount", title="Comment Count", frozen=True, exclude=True)
    like_count: int = Field(..., alias="LikeCount", title="Like Count", frozen=True, exclude=True)
    title: Optional[str] = Field(..., alias="Title", title="Title")
    body: Optional[str] = Field(..., alias="Body", title="Body")
    link_url: Optional[str] = Field(..., alias="LinkUrl", title="Link Url", frozen=True, exclude=True)
    is_rich_text: bool = Field(..., alias="IsRichText", title="Is Rich Text")
    related_record_id: Optional[str] = Field(
        ..., alias="RelatedRecordId", title="Related Record ID", frozen=True, exclude=True
    )
    inserted_by_id: str = Field(..., alias="InsertedById", title="InsertedBy ID", frozen=True, exclude=True)
    network_scope: Optional[NetworkScopeEnum] = Field(
        ..., alias="NetworkScope", title="Network Scope", frozen=True, exclude=True
    )
    visibility: Optional[VisibilityEnum] = Field(..., alias="Visibility", title="Visibility")
    best_comment_id: Optional[str] = Field(
        ..., alias="BestCommentId", title="Best Comment ID", frozen=True, exclude=True
    )
    has_content: bool = Field(..., alias="HasContent", title="Has Content", frozen=True, exclude=True)
    has_link: bool = Field(..., alias="HasLink", title="Has Link", frozen=True, exclude=True)
    has_feed_entity: bool = Field(
        ..., alias="HasFeedEntity", title="Has Feed Entity Attachment", frozen=True, exclude=True
    )
    has_verified_comment: bool = Field(
        ..., alias="HasVerifiedComment", title="Has Verified Comment", frozen=True, exclude=True
    )
    is_closed: bool = Field(..., alias="IsClosed", title="Is Closed", frozen=True, exclude=True)
    status: Optional[StatusEnum] = Field(..., alias="Status", title="Status")

    @property
    def parent_name(self):
        return self._get_connected_object_name(
            [
                "ADM_Acceptance_Criterion__c",
                "ADM_Additional_Field__c",
                "ADM_Agile_Health_Team_Configuration__c",
                "ADM_Application_Activity_Plan__c",
                "ADM_Application_Approver__c",
                "ADM_Application_Case_Properties__c",
                "ADM_Application_Cluster_Group_Link__c",
                "ADM_Application_Cluster_Group__c",
                "ADM_Application_Cluster_Instance_Pr_Link__c",
                "ADM_Application_Cluster__c",
                "ADM_Application_Task_Template__c",
                "ADM_Application__c",
                "ADM_Artifact_License_Information__c",
                "ADM_Artifact_Software_Tag__c",
                "ADM_Artifact_Usage__c",
                "ADM_Artifact__c",
                "ADM_Assignment_Rule__c",
                "ADM_Board_User_Preferences__c",
                "ADM_Bookmark__c",
                "ADM_Build__c",
                "ADM_Burndown_Item__c",
                "ADM_Case__c",
                "ADM_CertificationExamHistory__c",
                "ADM_CertificationObservations__c",
                "ADM_Certification__c",
                "ADM_Change_List__c",
                "ADM_Change_Traffic_Control_Lock_Role__c",
                "ADM_Cloud__c",
                "ADM_Coach__c",
                "ADM_Collaborator__c",
                "ADM_Color__c",
                "ADM_Column_History__c",
                "ADM_Column_Status_Assignment__c",
                "ADM_Column__c",
                "ADM_Comment__c",
                "ADM_Copy_Log__c",
                "ADM_Cost_Savings_Initiative__c",
                "ADM_Cost_Savings__c",
                "ADM_Coverage__c",
                "ADM_Deleted_Task__c",
                "ADM_DeploymentStagger__c",
                "ADM_Epic_Burndown_Item__c",
                "ADM_Epic_Theme_Assignment__c",
                "ADM_Epic__c",
                "ADM_Feature_Freeze_Exception_Request__c",
                "ADM_Feature_Freeze_Status__c",
                "ADM_Form_Question_Answer_Option__c",
                "ADM_Form_Question_Answer__c",
                "ADM_Form_Question_Link_Action__c",
                "ADM_Form_Question_Link__c",
                "ADM_Form_Question_Option__c",
                "ADM_Form_Question__c",
                "ADM_Form_Response__c",
                "ADM_Form_Tab__c",
                "ADM_Form__c",
                "ADM_Freeze_Report_Configuration__c",
                "ADM_Frequency__c",
                "ADM_GUS_Exception__c",
                "ADM_Gack_Case_Prediction__c",
                "ADM_Gack_Impact__c",
                "ADM_Goal__c",
                "ADM_Grievance_Tracker__c",
                "ADM_Impact_Type__c",
                "ADM_Impact__c",
                "ADM_Instance_Proxy__c",
                "ADM_Investigation_Exception__c",
                "ADM_Issue_Risk__c",
                "ADM_Kingdom_AppClusterGroup_Link__c",
                "ADM_License_Information__c",
                "ADM_License_Policy__c",
                "ADM_License_Validation__c",
                "ADM_Milestone__c",
                "ADM_Module__c",
                "ADM_Open_Work_Notification_Properties__c",
                "ADM_Package_Manifest__c",
                "ADM_Package__c",
                "ADM_Parent_Cloud__c",
                "ADM_Parent_Work__c",
                "ADM_Perforce_Connector__c",
                "ADM_Planned_Release_Burndown__c",
                "ADM_Planned_Release_Forecast__c",
                "ADM_Planned_Release__c",
                "ADM_Priority_Mapping__c",
                "ADM_Priority_Override__c",
                "ADM_Priority__c",
                "ADM_Product_Tag_Work_Metadata__c",
                "ADM_Product_Tag__c",
                "ADM_Record_Group_Item__c",
                "ADM_Record_Group__c",
                "ADM_Related_Suite_Execution__c",
                "ADM_Related_Test_Scenario_Bug__c",
                "ADM_Related_Test_Scenario__c",
                "ADM_Related_Test_Suite__c",
                "ADM_Release_Approval_Criterion__c",
                "ADM_Release_Branch_Status__c",
                "ADM_Release_Burndown_Item__c",
                "ADM_Release_CTC_Locks_Template__c",
                "ADM_Release_Case_Status__c",
                "ADM_Release_Cycle_Status__c",
                "ADM_Release_Event_Cluster_Link__c",
                "ADM_Release_Event_Template__c",
                "ADM_Release_Event__c",
                "ADM_Release_Freeze_Status__c",
                "ADM_Release_Signoff__c",
                "ADM_Release_Stamp_Batch_ID__c",
                "ADM_Release_Stamp_Cache__c",
                "ADM_Release_Windows__c",
                "ADM_Release__c",
                "ADM_Released_In__c",
                "ADM_Scrum_Team_Cache__c",
                "ADM_Scrum_Team_Member__c",
                "ADM_Scrum_Team__c",
                "ADM_Security_Assessment_Association__c",
                "ADM_Security_Assessment_Item__c",
                "ADM_Security_Assessment_Survey__c",
                "ADM_Security_Assessment_Tag__c",
                "ADM_Security_Assessment__c",
                "ADM_Security_Assurance_Team__c",
                "ADM_Security_Questionaire__c",
                "ADM_Security_Signoff__c",
                "ADM_Security_Survey_Action__c",
                "ADM_Service_Event__c",
                "ADM_Service_Incident__c",
                "ADM_Severity_Type__c",
                "ADM_Severity__c",
                "ADM_Signoff__c",
                "ADM_Slack_Queued_Message__c",
                "ADM_Software_Category__c",
                "ADM_Software_Tag__c",
                "ADM_Solution_Overview__c",
                "ADM_Sprint__c",
                "ADM_Status_History__c",
                "ADM_Status_Report__c",
                "ADM_Suite_Execution__c",
                "ADM_Tag_Assignment__c",
                "ADM_Task__c",
                "ADM_Team_Dependency__c",
                "ADM_Team_Name_History__c",
                "ADM_Team_Release__c",
                "ADM_Test_Execution__c",
                "ADM_Test_Failure_Lock_Metadata__c",
                "ADM_Test_Scenario_Theme_Assignment__c",
                "ADM_Test_Scenario__c",
                "ADM_Test_Suite__c",
                "ADM_Theme_Assignment__c",
                "ADM_Theme_Security_Assessment_Assignment__c",
                "ADM_Theme__c",
                "ADM_Third_Party_Software__c",
                "ADM_Time_Off_Log__c",
                "ADM_Trust_Incident_Problem__c",
                "ADM_Trust_Incident__c",
                "ADM_Trust_Service__c",
                "ADM_Type__c",
                "ADM_User_Business_Hours__c",
                "ADM_User_Product_Tag__c",
                "ADM_Work_Cache__c",
                "ADM_Work_Commitment__c",
                "ADM_Work_History__c",
                "ADM_Work_Manager_User_Preferences__c",
                "ADM_Work_Status__c",
                "ADM_Work_Subscriber__c",
                "ADM_Work_Template__c",
                "ADM_Work__c",
                "AHI_Team_Configuration__c",
                "AMD_Artifact_Usage__c",
                "AOF_Area_Team__c",
                "AOF_Area_of_Focus__c",
                "AOF_Assignment__c",
                "AOF_CCE_Cloud__c",
                "AOF_Healthcheck_Delivery__c",
                "AOF_Healthcheck_Requirement__c",
                "AOF_Tag_Assignment_Change__c",
                "AP_DRB_Custom_Component__c",
                "AP_DRB_Custom_Property_Editor__c",
                "AP_DRB_Cx_Ui_Text_Review__c",
                "AP_DRB_Feature__c",
                "AP_DRB_Flow__c",
                "AP_DRB_IA_Error__c",
                "AP_DRB_InvocableAction__c",
                "AP_DRB_Object__c",
                "AP_DRB_Process_Type__c",
                "AP_DRB_Request__c",
                "AP_DRB_Submission__c",
                "ASA_Survey_Question_Relation__c",
                "ASA_Survey_Question__c",
                "ASA_Survey_Response__c",
                "ASA_Survey__c",
                "Account",
                "Account_Org__c",
                "Applied_BOM_Rule_Log_Entity_Connector__c",
                "Asset",
                "AssetRelationship",
                "Assetforce_Application__c",
                "BTR_Black_Tab_Request_Result__c",
                "BTR_Black_Tab_Request_Scope__c",
                "BTR_Black_Tab_Request__c",
                "BT_Org_Settings__c",
                "BT_Single_Setting_Output__c",
                "Biz_Tech_CD_Jenkins_Build__c",
                "Biz_Tech_CD_Jenkins_Job__c",
                "CAB_Patch_Candidate__c",
                "CCE_InvCloseSummary__c",
                "CCE_Production_Debugger_Request__c",
                "CCE_Scorecard__c",
                "CCE_StructInvTemplate__c",
                "CCE_StructInv__c",
                "CMPLC_Data_Privacy_Cleanup__c",
                "CMPLC_FedRamp_High_Exception_Tracker__c",
                "CMPLC_FedRamp_High_Release_Sign_Off__c",
                "CMPLC_Log_Record_Exception__c",
                "CMPLC_Log_Record__c",
                "CMPLC_Violation__c",
                "CMP__c",
                "COL_Calculation_Item__c",
                "COL_Calculation__c",
                "COL_Request_Consolidated_Order_Connector__c",
                "COM_Budget_Category__c",
                "COM_Business_Unit__c",
                "COM_Cost_Center__c",
                "COM_Notification_Type__c",
                "CPO_Perf_Cloud_Status__c",
                "CPO_Perf_Cloud_Team__c",
                "CPO_Perf_Meta__c",
                "CPO_Perf_Todo__c",
                "CTC_SETTINGS__c",
                "CaPAD_Allocation_Tracker__c",
                "CaPAD_CDR_View_Settings__c",
                "CaPAD_COI_Metrics__c",
                "CaPAD_COI_RedirectCOI_Connector__c",
                "CaPAD_CO_Item_Rack_and_Roll_Connector__c",
                "CaPAD_CO_Metrics__c",
                "CaPAD_CRItem_COItem_Connector__c",
                "CaPAD_CR_Metrics__c",
                "CaPAD_Capacity_Delivery_Record__c",
                "CaPAD_Capacity_Request_BOM_Templates__c",
                "CaPAD_Capacity_Request_Item_Type__c",
                "CaPAD_Capacity_Request__c",
                "CaPAD_Case_Connector__c",
                "CaPAD_Case_Metrics__c",
                "CaPAD_Certificate_of_Acceptance__c",
                "CaPAD_Consolidated_Order_Facility__c",
                "CaPAD_Consolidated_Order_Item__c",
                "CaPAD_Consolidated_Order__c",
                "CaPAD_Delivery_Summary__c",
                "CaPAD_FCO_Metrics__c",
                "CaPAD_Purchase_Order_Line__c",
                "CaPAD_Purchase_Order__c",
                "CaPAD_Purchase_Requisition_Line__c",
                "CaPAD_Purchase_Requisition__c",
                "CaPAD_Rack_Architecture_Rule_Connector__c",
                "CaPAD_Rack_and_Roll_CO_Item__c",
                "CaPAD_SKU_BOMTemplate_Connector__c",
                "CaPlan_Applied_BOM_Template_Rule__c",
                "CaPlan_Applied_RnR_Rack__c",
                "CaPlan_BOM_Template_Rule_Filter__c",
                "CaPlan_BOM_Template_Rule__c",
                "CaPlan_Capacity_Roadmap_Amended_Item__c",
                "CaPlan_Capacity_Roadmap__c",
                "CaPlan_Operations_Monitor__c",
                "CaPlan_Org_Migration_Communication__c",
                "CaPlan_Org_Migration_Deferral__c",
                "CaPlan_Org_Migration_Schedulability__c",
                "CaPlan_Publication_Index__c",
                "CaffeineWorker__c",
                "Campaign",
                "CapFin_BR_Approval_Policy_User__c",
                "CapFin_BR_Approval_Policy__c",
                "CapFin_BR_Category__c",
                "CapFin_BR_FD_Budget_Approval__c",
                "CapFin_BR_Monthly_Cost_Savings__c",
                "CapFin_BR_Product__c",
                "CapFin_Budget_Impact__c",
                "CapFin_Budget_Request_Item__c",
                "CapFin_Budget_Request__c",
                "CapFin_Falcon_Item_Price__c",
                "CapFin_PID__c",
                "CapFin_SF_Product__c",
                "Capacity_Budget_Request_Service__c",
                "Capfin_BR_Approval_FIFD__c",
                "Capfin_BR_Budget_Owner__c",
                "Capfin_BR_Owner__c",
                "Case",
                "Case_To_Theme_Connector__c",
                "Challenge_Activity__c",
                "Challenge_Participant__c",
                "Challenge_Template__c",
                "Challenge__c",
                "Change_Implementation_Step_to_CI__c",
                "CollaborationGroup",
                "Comms_for_Sev0_Sev1_incidents__c",
                "Contact",
                "ContentDocument",
                "Contract",
                "ContractLineItem",
                "DCIM_Breaker__c",
                "DCIM_Cell_PoP_Connector__c",
                "DCIM_Cell__c",
                "DCIM_Connection_Type__c",
                "DCIM_Datacenter_Provider__c",
                "DCIM_Enclosure_Type__c",
                "DCIM_Enclosure__c",
                "DCIM_EndFeed_Rack_Connector__c",
                "DCIM_EndFeed__c",
                "DCIM_Facility_Contract__c",
                "DCIM_Facility__c",
                "DCIM_Infrastructure_Group__c",
                "DCIM_Measured_Power__c",
                "DCIM_Metro_Area__c",
                "DCIM_Module_Possible_Rack_Architectures__c",
                "DCIM_Module_Template_Tile_Nodes__c",
                "DCIM_Module_Template_Tiles__c",
                "DCIM_Module_Type_Network_Template__c",
                "DCIM_Module_Type__c",
                "DCIM_Module__c",
                "DCIM_Network_Architecture__c",
                "DCIM_Network_Group_Connection_Template__c",
                "DCIM_Network_Group_Node_Template__c",
                "DCIM_Network_Group_Template__c",
                "DCIM_Network_Group__c",
                "DCIM_Node_Class__c",
                "DCIM_Node_Connection__c",
                "DCIM_Node_Type__c",
                "DCIM_Node__c",
                "DCIM_PDU__c",
                "DCIM_PoP__c",
                "DCIM_Possible_Rack_Architecture__c",
                "DCIM_Rack_Architecture_Node_Assignment__c",
                "DCIM_Rack_Architecture_Type_Assignment__c",
                "DCIM_Rack_Architecture__c",
                "DCIM_Rack_Class__c",
                "DCIM_Rack_Tile_Lifecycle_Metrics__c",
                "DCIM_Rack_Unit_Assignment__c",
                "DCIM_Rack_Unit__c",
                "DCIM_Rack__c",
                "DCIM_Room_Contracts__c",
                "DCIM_Room_PDU_Connector__c",
                "DCIM_Room__c",
                "DCIM_Server_Architecture__c",
                "DCIM_Server_Class__c",
                "DCIM_Supported_Network_Architecture__c",
                "DCIM_Vendor_Reported_Power__c",
                "DCOM_Decommission_Request_Metrics__c",
                "DCOM_Decommission_Request__c",
                "DCOM_Host_Decommission_Record_Metrics__c",
                "DCOM_Host_Decommission_Record_Work_Item__c",
                "DCOM_Host_Decommission_Record__c",
                "DCOM_Rack_Decommission_Record__c",
                "DD_App_To_Object_Connector__c",
                "DD_App__c",
                "DD_Field__c",
                "DD_Object__c",
                "DD_Validation_Rules__c",
                "Dashboard",
                "DashboardComponent",
                "EDI_Asset_Staging__c",
                "EMOTP__c",
                "ENB_Enablement_Project_Proposal__c",
                "ENB_Intake__c",
                "Education__c",
                "Endorsement__c",
                "EnhancedLetterhead",
                "Entitlement",
                "Environments_Order__c",
                "Event",
                "FKP_Request__c",
                "FOX_Capacity_Plan__c",
                "FOX_Falcon_GovCloud_Instance__c",
                "FOX_Falcon_Instance__c",
                "FOX_Functional_Domain_Instance__c",
                "FOX_Functional_Domain__c",
                "FOX_Parent_Cloud_Banner__c",
                "FOX_Parent_Cloud_to_PLR_Product__c",
                "FOX_Request__c",
                "FOX_Request_to_Change_Category__c",
                "FOX_Request_to_FD__c",
                "FOX_Request_to_FOX_Service__c",
                "FOX_Service_Doc__c",
                "FOX_Service_Group__c",
                "FOX_Service_Group_to_FOX_Service__c",
                "FOX_Service_Owner_Member__c",
                "FOX_Service_Owner__c",
                "FOX_Service__c",
                "FOX_Step__c",
                "FOX_Step_to_SA__c",
                "FOX_Step_to_Security_Signoff__c",
                "FOX_Step_to_Work__c",
                "FOX_Type__c",
                "FOX_Type_to_Step__c",
                "FOX_to_FOT_Data__c",
                "Feature_Group__c",
                "Feature_Group_to_Story_Map__c",
                "Feature_Metrics__c",
                "Feedback_Comment__c",
                "Feedback__c",
                "GIDX_Category__c",
                "GIDX_FAQ_QandA__c",
                "GIDX_FAQ_Topic__c",
                "GIDX_Idea__c",
                "GIDX_Vote__c",
                "GLUE_Allow_List_Entry__c",
                "GLUE_Allow_List__c",
                "GLUE_Artifact_Campaign__c",
                "GLUE_Campaign_Project__c",
                "GLUE_Exception__c",
                "GLUE_General_Artifact__c",
                "GLUE_General_Campaign__c",
                "GLUE_artifact__x",
                "GLUE_artifact_usage__x",
                "GLUE_controller__x",
                "GLUE_controller_method_exploit__x",
                "GLUE_cookie__x",
                "GLUE_cve__x",
                "GT_TaniumCaseSyncStatus__c",
                "INN_Entity__c",
                "INN_InnovationAccelerator__c",
                "INN_Innovation_Idea_Team_Member__c",
                "INN_Innovation_Idea_Work__c",
                "INN_Innovation_Idea__c",
                "IP_Playbook_Record__c",
                "IP_Playbook_Record_v2__c",
                "ITSM_BOM_Template_CatalogItem__c",
                "ITSM_Catalog__c",
                "ITSM_TP_CatalogItem_TAT_Junction__c",
                "ITSM_TP_CatalogItem__c",
                "Incident_Participant__c",
                "Incident_to_CI__c",
                "Innovation__c",
                "Innovation_and_Inventor__c",
                "Knowledge__ka",
                "LAP_Admin_Delegate__c",
                "LAP_Decision_Maker__c",
                "LAP_Decision_Step__c",
                "LAP_Decision__c",
                "LAP_Type_and_LAP_Steps__c",
                "LIT_Component_Release_History__c",
                "LIT_Lightning_Component__c",
                "LIT_Lightning_Page_Component_Association__c",
                "LIT_Lightning_Page__c",
                "Lead",
                "LinkedArticle",
                "Locking_Record__c",
                "Log_Type__c",
                "MDS_Attribute__c",
                "MDS_CanonicalAttributeMapping__c",
                "MDS_EntityGroup__c",
                "MDS_Entity_Access_Control_Information__c",
                "MDS_Entity__c",
                "MDS_SubjectArea__c",
                "MakeMobile__MakeMobile_Application__c",
                "OBR_Onboarding_Request__c",
                "OE_Judge__c",
                "OE_Nomination_Period__c",
                "OE_Nomination__c",
                "OE_Nominee__c",
                "OE_OmOpportunity__c",
                "OE_Oom_Application__c",
                "OMOpportunity__c",
                "ONC_Duty__c",
                "ONC_Event_Coverage_Template__c",
                "ONC_Event_Coverage__c",
                "OOM_Interviewer__c",
                "OOM_Welcome_Info_Section__c",
                "OOM_Welcome_Team_Video__c",
                "ORD_ISC__c",
                "ORD_ORD__c",
                "OSS_Project__c",
                "OSS_Task__c",
                "Opportunity",
                "PF_Product_Feature_Inventory__c",
                "PLR_Product_Legal_Request__c",
                "PLR_Product__c",
                "PLR_Type__c",
                "PPM_Budget_Request__c",
                "PPM_Portfolio__c",
                "PPM_Program_Area__c",
                "PPM_Program_Theme_Assignment__c",
                "PPM_Program__c",
                "PPM_Project_Accomplishment__c",
                "PPM_Project_Dependency__c",
                "PPM_Project_Issue__c",
                "PPM_Project_Risk__c",
                "PPM_Project_Theme_Assignment__c",
                "PPM_Project__c",
                "PPM_Request__c",
                "PPM_Resources__c",
                "PTON_Project__c",
                "PTOn_Category__c",
                "PTOn_Participant__c",
                "PTOn_Project_History__c",
                "PVT_Result_Stats__c",
                "PVT_Rules_Cache__c",
                "PVT_Stat_Queue__c",
                "PVT_Test_Result__c",
                "PVT_Test_Rule__c",
                "Planning_Session_Statistic__c",
                "Planning_Session__c",
                "Point_Assignment__c",
                "Position__c",
                "Product2",
                "Product_Metrics__c",
                "ProfileSkill",
                "ProfileSkillEndorsement",
                "ProfileSkillUser",
                "Profile_Summary__c",
                "Q3E_Blitz_Feature_Lead__c",
                "Q3E_Blitz_Participant__c",
                "Q3E_Blitz__c",
                "QA_Comment__c",
                "QA_Default_Test_Case__c",
                "QA_ExecutionBug__c",
                "QA_FTest__c",
                "QA_Hierarchy__c",
                "QA_Question__c",
                "QA_Test_Case__c",
                "QA_Test_Execution__c",
                "QA_Test_Plan__c",
                "RB_Retrospective_Active_User__c",
                "RB_Retrospective_Column__c",
                "RB_Retrospective_Facilitator__c",
                "RB_Retrospective_Item_Comment__c",
                "RB_Retrospective_Item__c",
                "RB_Retrospective__c",
                "RCA__c",
                "RSTR_L1_Product_Shared_Service__c",
                "RSTR_L2_Product_Shared_Service__c",
                "Related_Team_Dependency__c",
                "Release_Signoff_Infrastructure__c",
                "Report",
                "SAA_Comms_Service_Config__c",
                "SAA_Comms_Service_Field_Update__c",
                "SAA_Comms_Service_Filter_Condition__c",
                "SAA_Comms_Service_Report_Link__c",
                "SAA_Comms_Service_SA_History__c",
                "SAA_Engagement_Group_c__x",
                "SDS_AST__Repos_master__c",
                "SDS_Zones_Intake__c",
                "SDS_Zones_Policy__c",
                "SDS_Zones_Questionnaire_Option__c",
                "SDS_Zones_Questionnaire_Survey__c",
                "SDS_Zones_Survey_Results__c",
                "SFQA_Post_Tags__c",
                "SFQA_Post__c",
                "SFQA_Tag__c",
                "SFQA_Team__c",
                "SFQA_Vote__c",
                "SF_Test_Manager__TM_Context__c",
                "SLA_Violation__c",
                "SLL_Locking_Rule__c",
                "SM_APM_Availability_Unit_History__c",
                "SM_APM_Availability_Unit__c",
                "SM_APM_Cloud__c",
                "SM_APM_Customer_Trust_Incident__c",
                "SM_APM_Product_Family__c",
                "SM_APM_Product__c",
                "SM_APM_Service_Avail_Unit_Junction__c",
                "SM_APM_Service__c",
                "SM_APM_Sub_Availability_Unit__c",
                "SM_Account_Service__c",
                "SM_Actual_Downtime__c",
                "SM_AlertProductTagToCaseRecTypeMapping__c",
                "SM_Alert_Assignment_Rule__c",
                "SM_Alert_Automation_Audit__c",
                "SM_Alert_Automation_Rule_Action__c",
                "SM_Alert_Automation_Rule__c",
                "SM_Alert_Notification_Rule__c",
                "SM_Alert_Notification__c",
                "SM_Alert__c",
                "SM_Application_Versions__c",
                "SM_Approval_Request_Rejection_Category__c",
                "SM_Approval_Request_Rejection_Reason__c",
                "SM_Asset_Type_Canonical_Name__c",
                "SM_BOM_Item__c",
                "SM_BOM_Template_Item__c",
                "SM_BOM_Template__c",
                "SM_Block_Suppression__c",
                "SM_Block__c",
                "SM_Bridge__c",
                "SM_Business_Name__c",
                "SM_Capacity_Build_Group__c",
                "SM_CaseRecTypeToQueueIdMapping__c",
                "SM_Case_Approval_History__c",
                "SM_Case_Approval_Request_Rejection__c",
                "SM_Case_Asset_Connector__c",
                "SM_Case_Asset_Type_Connector__c",
                "SM_Case_ContributingFactors__c",
                "SM_Case_Notification_Audit__c",
                "SM_Case_Notification_Rule__c",
                "SM_Case_Notification__c",
                "SM_Case_Time_Tracker__c",
                "SM_Case_To_Comment_Tracking__c",
                "SM_Case_to_DCP_Connector__c",
                "SM_Case_to_Instance_Connector__c",
                "SM_Case_to_LogicalHost_Connector__c",
                "SM_Case_to_Vendor_Connector__c",
                "SM_ChangeToIncident__c",
                "SM_Change_Approval_Process__c",
                "SM_Change_Approval_Step__c",
                "SM_Change_Case_Risk_Analyzer__c",
                "SM_Change_Category__c",
                "SM_Change_Compliance__c",
                "SM_Change_Courier_Destination__c",
                "SM_Change_Courier__c",
                "SM_Change_Implementation__c",
                "SM_Change_Implementation_to_Inst_Conn__c",
                "SM_Change_Type__c",
                "SM_Cloud_Team__c",
                "SM_Cluster__c",
                "SM_Company__c",
                "SM_Compliance_ControlDefinition__c",
                "SM_Compliance_Message__c",
                "SM_Compliance_Notification__c",
                "SM_Compliance__c",
                "SM_Configuration__c",
                "SM_Contributing_Category__c",
                "SM_Contributing_Factor__c",
                "SM_Control_Definition__c",
                "SM_Control_Tracking__c",
                "SM_Customer_Service__c",
                "SM_DCP_Action_Comment__c",
                "SM_DCP_Action__c",
                "SM_DCP_Asset_Connector__c",
                "SM_Database_Model__c",
                "SM_Dcp_Request__c",
                "SM_Delete_Audit_Trail__c",
                "SM_EXT_ENTITYCASE_API__c",
                "SM_End_of_Service_Life_Asset_Type_Record__c",
                "SM_End_of_Service_Life_Replacement_Opt__c",
                "SM_Epic_To_LifeCycle_Map__c",
                "SM_Evidence_Repository__c",
                "SM_Facility_Kingdom_Connector__c",
                "SM_Falcon_FD_Service_Stamp_Junction__c",
                "SM_Falcon_FI_FD_Stamp_Junction__c",
                "SM_Falcon_FunctionalDomain_Stamp__c",
                "SM_Falcon_FunctionalInstance_Stamp__c",
                "SM_Financial_Sync_Mismatch_Item__c",
                "SM_Financial_Sync_Schedule__c",
                "SM_Financial_Sync__c",
                "SM_General_Picklist__c",
                "SM_GocConstants__c",
                "SM_GocFilter__c",
                "SM_GocSettings__c",
                "SM_Hammer_Task_Record__c",
                "SM_Hammer_Task__c",
                "SM_Hard_Drive_Data__c",
                "SM_Host_Imaging_Logs__c",
                "SM_IP_Ranges__c",
                "SM_Import_Log__c",
                "SM_IncidentParticipants__c",
                "SM_Incident_TTX_Metric__c",
                "SM_Incident_Timestamp__c",
                "SM_Incident_Update_Metric__c",
                "SM_Infrastructure_Extension_Request__c",
                "SM_Instance_Datacenter_Connector__c",
                "SM_Kingdom__c",
                "SM_Landing_Page_Configuration__c",
                "SM_Leaf_Node__c",
                "SM_LifeCycle_Map__c",
                "SM_Logical_Entity__c",
                "SM_Logical_Host__c",
                "SM_Logical_Host_to_Cluster_Connector__c",
                "SM_Logs__c",
                "SM_Manufacturer_Part__c",
                "SM_Message_Queue_Suspend_Data__c",
                "SM_Message_Type__c",
                "SM_Network_Group__c",
                "SM_Network_Node__c",
                "SM_Order_Cycle__c",
                "SM_Parts_Locker_Eligible__c",
                "SM_Pipeline__c",
                "SM_Pod_Task_Tracker__c",
                "SM_Pricing_Detail__c",
                "SM_Problem_Acc_Junction__c",
                "SM_Problem_Attendee_junction__c",
                "SM_Problem_Contributing_Factors__c",
                "SM_Problem_Work_Junction__c",
                "SM_Problem__c",
                "SM_Production_Instance_Work_Item__c",
                "SM_Production_Instance__c",
                "SM_RMA_Outgoing_Transactions__c",
                "SM_Region__c",
                "SM_Release_Audit__c",
                "SM_Reliability_Gap__c",
                "SM_Requested_End_Date_Change_Tracker__c",
                "SM_Root_Cause__c",
                "SM_Scheduled_Downtime__c",
                "SM_Service_Management_Logging_Apps__c",
                "SM_Shared_Vendor_Attachments__c",
                "SM_Split_Migration_Information__c",
                "SM_Sql_Script_Output__c",
                "SM_Storage_To_IDC_Connector__c",
                "SM_Suspend_Queue_Org__c",
                "SM_Task_Item__c",
                "SM_Task_Template_Item__c",
                "SM_Tasks_Template__c",
                "SM_TechAssetType_LeadTime__c",
                "SM_TechOps_Vendors__c",
                "SM_Transaction__c",
                "SM_Use_Policy__c",
                "SM_VENDOR_API_TRANSLATE__c",
                "SM_VIP__c",
                "SOMM_Lane__c",
                "SOMM__c",
                "SP_Protection_Action__c",
                "SP_Protection_Event__c",
                "SRVCAT_Security_Assessments_Services__c",
                "SUM_Splunk_Usage__c",
                "Score__c",
                "Semantic_Expertise__c",
                "ServiceContract",
                "Service_Product_Tag_Connector__c",
                "Service_Role_Connector__c",
                "Service_Security_Metadata__c",
                "Service__c",
                "Site",
                "SkillRequirement",
                "Skill_Category__c",
                "Skill__c",
                "Snip_CodeSnippet__c",
                "Solution",
                "SplitOrgMapStore__c",
                "SplitStateStore__c",
                "Success_Metric__c",
                "Survey",
                "TC_Break_Glass_Record__c",
                "TC_Tool_Catalog__c",
                "TC_Tool_Exception__c",
                "TC_Tool_Mapping__c",
                "TH_Suggested_Badge_Trail_Relationship__c",
                "TPIL_Documents__c",
                "TPIL_MatrixMetricBlacklist__c",
                "TPIL_MatrixMetricValue__c",
                "TPIL_MatrixMetric__c",
                "TPIL_TagAssignment__c",
                "TPIL_Tag__c",
                "TPIL_User_Preference__c",
                "TPQ__Sec_Answer_General__c",
                "TPQ__Sec_Answer__c",
                "TPQ__Sec_Proj_Gen__c",
                "TPQ__Sec_Project_Ownership_Team__c",
                "TPQ__Sec_Quest_Poss_Ans__c",
                "TPQ__Sec_Question__c",
                "TVM_Vulnerability_Assignment__c",
                "TVM_Vulnerability__c",
                "Task",
                "TechAsset_Lifecycle_Metrics__c",
                "TechAsset_supportforceHistory__c",
                "Tech_Asset_Archive_History__c",
                "Tech_Asset_Connector__c",
                "Tech_Asset_Location__c",
                "Tech_Asset_NetInterfaces__c",
                "Tech_Asset_Peripheral__c",
                "Tech_Asset_Role__c",
                "Tech_Asset_Type_Category_Type__c",
                "Tech_Asset_Type_Category__c",
                "Tech_Asset_Type_Make__c",
                "Tech_Asset_Type_Manufacturer__c",
                "Tech_Asset_Types__c",
                "Tech_Asset__c",
                "ThreatModeling__ThreatModelingQuestion__c",
                "Topic",
                "Trend_Metric__c",
                "Trlhd_Badge_History_Log__c",
                "Trlhd_Badge_Metric__c",
                "Trlhd_Badge_Prerequisite__c",
                "Trlhd_Badge__c",
                "Trlhd_Benchmark_Category__c",
                "Trlhd_Benchmark_Relationship__c",
                "Trlhd_Content_Feedback__c",
                "Trlhd_Content_Request__c",
                "Trlhd_Content_Version__c",
                "Trlhd_Debug_Log__c",
                "Trlhd_Interaction_Badge_Relationship__c",
                "Trlhd_Interaction__c",
                "Trlhd_Learner_Demographic_Metric__c",
                "Trlhd_Manifest_Item__c",
                "Trlhd_Release__c",
                "Trlhd_Suggested_Metadata__c",
                "Trlhd_Team__c",
                "Trlhd_Trail_Badge__c",
                "Trlhd_Trail__c",
                "Trlhd_Trailmix_Component__c",
                "Trlhd_Trailmix__c",
                "Trlhd_Unit__c",
                "Trust_Incident__c",
                "User",
                "V2G_Measure__c",
                "V2G_Owner__c",
                "V2G_V2MOM_Method__c",
                "V2G_V2MOM__c",
                "Value_Score__c",
                "Vendor_Information__c",
                "VoiceCall",
                "WorkBadgeDefinition",
                "eRelease_Request__c",
                "goc__Change__c",
                "goc__Configuration_Item_Activity__c",
                "goc__Configuration_Item_Lock_Activity__c",
                "goc__Configuration_Item_Lock_Exception__c",
                "goc__Configuration_Item_Lock_Group__c",
                "goc__Configuration_Item_Lock_Type_Exemption__c",
                "goc__Configuration_Item_Lock_Type__c",
                "goc__Configuration_Item_Lock__c",
                "goc__Configuration_Item_Type__c",
                "goc__Configuration_Item__c",
                "goc__Conflicting_Lock_Type__c",
                "goc__Feature_Settings__c",
                "goc__Lock_Type_Category__c",
                "gus2click__ClickSoftwareCase__c",
                "handover__HO_Handover_Item__c",
                "handover__HO_Handover_Shift__c",
                "handover__HO_Handover_Team__c",
                "handover__HO_Handover_Type__c",
                "handover__HO_Handover__c",
                "handover__Handover_Item__c",
                "handover__Handover_Shift__c",
                "handover__Handover_Type__c",
                "handover__Handover__c",
                "infraeng__ACL_Kingdom__c",
                "infraeng__ACL_Request__c",
                "infraeng__Availability_Group_Work_Item__c",
                "infraeng__Availability_Group__c",
                "infraeng__CPT_Onboarding__c",
                "infraeng__Captain_DC__c",
                "infraeng__Decomm_Dashboard__c",
                "infraeng__Decomm_Host__c",
                "infraeng__Decommission__c",
                "infraeng__FFP_Scope_Request_Approver__c",
                "infraeng__FFP_Scope_Request__c",
                "infraeng__Falcon_Onboarding_Approval__c",
                "infraeng__Falcon_Onboarding_Item__c",
                "infraeng__Host_Work_Item__c",
                "infraeng__ISE_Tool_Config__c",
                "infraeng__LEO_Host__c",
                "infraeng__MSED_Exception__c",
                "infraeng__Patch_Bundle_State_Item__c",
                "infraeng__Patch_Bundle__c",
                "infraeng__Patch_Instance__c",
                "infraeng__Patch_Sign_Off__c",
                "infraeng__Patch__c",
                "infraeng__Projected_Target_Date__c",
                "infraeng__cAPS_Role_Team_Mapping__c",
                "items_Google_Drive__x",
                "ks_File_Loss__c",
                "oss_dashboard__Open_Source_GitHub_Org__c",
                "oss_dashboard__Open_Source_GitHub_Repo__c",
                "sf_cla__CLA_Signature__c",
                "sfcerts__Approval_Report_Item__c",
                "sfcerts__Approval_Report__c",
                "sfcerts__Bulk_Certificate_Request__c",
                "sfcerts__CS_Toolkit_Info__c",
                "sfcerts__Certificate_Extension__c",
                "sfcerts__Certificate_Request__c",
                "sfcerts__Certificate__c",
                "sfcerts__Domain__c",
                "sfcerts__Issuer__c",
                "sfcerts__Key_Storage_Info__c",
                "sfcerts__Organization__c",
                "sfcerts__Policy_Exception_Request__c",
                "sfcerts__SOR_Info_Item__c",
                "sfcerts__SOR_Info__c",
                "sfcerts__SOR_Record__c",
                "sfcerts__Validation_Report__c",
                "sfcerts__Vendor__c",
                "sfhackday__Category__c",
                "sfhackday__Entry_Category__c",
                "sfhackday__Entry__c",
                "sfhackday__Event__c",
                "sfhackday__Participant__c",
                "sfhackday__Vote__c",
            ],
            self.parent_id,
        )

    @property
    def created_by_name(self):
        return self._get_connected_object_name(["SelfServiceUser", "User"], self.created_by_id)

    @property
    def last_edit_by_name(self):
        return self._get_connected_object_name(["SelfServiceUser", "User"], self.last_edit_by_id)

    @property
    def related_record_name(self):
        return self._get_connected_object_name(
            ["ContentVersion", "ProfileSkillUser", "WorkThanks"], self.related_record_id
        )

    @property
    def inserted_by_name(self):
        return self._get_connected_object_name(["SelfServiceUser", "User"], self.inserted_by_id)

    @property
    def best_comment_name(self):
        return self._get_connected_object_name(["FeedComment"], self.best_comment_id)

    def __init__(self, **kwargs: Any):
        """
        Initialize Salesforce Object.

        :param **kwargs: keyword arguments
        """
        super().__init__(**kwargs)

    @property
    def web_url(self) -> str:
        """
        Web URL.

        :returns: web url
        """
        return f"https://{GUSClient.instance().sf.sf_instance}/{self.id_}"

    @classmethod
    def get_by_id(cls, id_: str) -> Self:
        """
        Get feed item.

        :param id_: Salesforce Object Id
        :returns: Feed Item object
        """
        x = GUSClient.instance().sf.__getattr__("FeedItem").get(id_)
        return FeedItem(**{"sf": GUSClient.instance().sf, **x})

    @classmethod
    def create(cls, **kwargs: Any) -> Self:
        """
        Create feed item.
        :param **kwargs: values for the fields of the Feed Item object
        :returns: Feed Item object
        :raises RuntimeError: if object creation failed
        """
        lookup = cls._get_field_to_sf_name_dict()
        fields = {lookup[k]: v for k, v in kwargs.items()}
        return cls._create("FeedItem", fields)

    @classmethod
    def update(cls, model: Self, headers: Optional[Dict[str, str]] = None) -> None:
        """
        Update Salesforce API with changes.
        :param model: Feed Item object to update
        :param headers: headers to send with REST call
            https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers.htm
        """

        updates = model.model_dump_json(by_alias=True, exclude_unset=True, exclude_defaults=True, exclude_none=True)
        import json

        updates = json.loads(updates)  # TODO - better way to do this?
        if updates:
            GUSClient.instance().sf.__getattr__("FeedItem").update(model.id_, updates, headers=headers)

    @classmethod
    def soql_query(cls, where_clause: str) -> Generator[Self, None, None]:
        """
        Query Feed Items by SOQL WHERE clause.

        :param where_clause: where clause of SOQL query
        :yields: Feed Item objects
        """
        for x in cls._query_soql("FeedItem", where_clause):
            yield FeedItem(**x)
