"""User."""
# Do not Edit this file.
# This file is generated from the "gitgus dev generate-sobjects" command
#
# Remember, you can always regenerate this file by running the above command.
# If you have made changes to this file, they will be lost.
# Edit template: sobject.py.jinja2

from datetime import date
from datetime import datetime
from enum import Enum
from typing import Any
from typing import Self
from typing import Dict
from typing import List
from typing import Optional
from typing import Generator

from pydantic import Field, ConfigDict, computed_field
from ..gus_client import GUSClient
from .sobject_base import SObjectBase, SObjectType


class GeocodeAccuracyEnum(str, Enum):
    """Geocode Accuracy."""

    OPTION_0 = "Address"
    OPTION_1 = "NearAddress"
    OPTION_2 = "Block"
    OPTION_3 = "Street"
    OPTION_4 = "ExtendedZip"
    OPTION_5 = "Zip"
    OPTION_6 = "Neighborhood"
    OPTION_7 = "City"
    OPTION_8 = "County"
    OPTION_9 = "State"
    OPTION_10 = "Unknown"


class TimeZoneSidKeyEnum(str, Enum):
    """Time Zone."""

    OPTION_0 = "Pacific/Kiritimati"
    OPTION_1 = "Pacific/Enderbury"
    OPTION_2 = "Pacific/Tongatapu"
    OPTION_3 = "Pacific/Chatham"
    OPTION_4 = "Asia/Kamchatka"
    OPTION_5 = "Pacific/Auckland"
    OPTION_6 = "Pacific/Fiji"
    OPTION_7 = "Pacific/Guadalcanal"
    OPTION_8 = "Pacific/Norfolk"
    OPTION_9 = "Australia/Lord_Howe"
    OPTION_10 = "Australia/Brisbane"
    OPTION_11 = "Australia/Sydney"
    OPTION_12 = "Australia/Adelaide"
    OPTION_13 = "Australia/Darwin"
    OPTION_14 = "Asia/Seoul"
    OPTION_15 = "Asia/Tokyo"
    OPTION_16 = "Asia/Hong_Kong"
    OPTION_17 = "Asia/Kuala_Lumpur"
    OPTION_18 = "Asia/Manila"
    OPTION_19 = "Asia/Shanghai"
    OPTION_20 = "Asia/Singapore"
    OPTION_21 = "Asia/Taipei"
    OPTION_22 = "Australia/Perth"
    OPTION_23 = "Asia/Bangkok"
    OPTION_24 = "Asia/Ho_Chi_Minh"
    OPTION_25 = "Asia/Jakarta"
    OPTION_26 = "Asia/Rangoon"
    OPTION_27 = "Asia/Dhaka"
    OPTION_28 = "Asia/Kathmandu"
    OPTION_29 = "Asia/Colombo"
    OPTION_30 = "Asia/Kolkata"
    OPTION_31 = "Asia/Karachi"
    OPTION_32 = "Asia/Tashkent"
    OPTION_33 = "Asia/Yekaterinburg"
    OPTION_34 = "Asia/Kabul"
    OPTION_35 = "Asia/Baku"
    OPTION_36 = "Asia/Dubai"
    OPTION_37 = "Asia/Tbilisi"
    OPTION_38 = "Asia/Yerevan"
    OPTION_39 = "Africa/Cairo"
    OPTION_40 = "Africa/Nairobi"
    OPTION_41 = "Asia/Baghdad"
    OPTION_42 = "Asia/Beirut"
    OPTION_43 = "Asia/Jerusalem"
    OPTION_44 = "Asia/Kuwait"
    OPTION_45 = "Asia/Riyadh"
    OPTION_46 = "Europe/Athens"
    OPTION_47 = "Europe/Bucharest"
    OPTION_48 = "Europe/Helsinki"
    OPTION_49 = "Europe/Istanbul"
    OPTION_50 = "Europe/Minsk"
    OPTION_51 = "Europe/Moscow"
    OPTION_52 = "Africa/Johannesburg"
    OPTION_53 = "Europe/Amsterdam"
    OPTION_54 = "Europe/Berlin"
    OPTION_55 = "Europe/Brussels"
    OPTION_56 = "Europe/Paris"
    OPTION_57 = "Europe/Prague"
    OPTION_58 = "Europe/Rome"
    OPTION_59 = "Africa/Algiers"
    OPTION_60 = "Africa/Casablanca"
    OPTION_61 = "Europe/Dublin"
    OPTION_62 = "Europe/Lisbon"
    OPTION_63 = "Europe/London"
    OPTION_64 = "America/Scoresbysund"
    OPTION_65 = "Atlantic/Azores"
    OPTION_66 = "GMT"
    OPTION_67 = "Atlantic/Cape_Verde"
    OPTION_68 = "Atlantic/South_Georgia"
    OPTION_69 = "America/St_Johns"
    OPTION_70 = "America/Argentina/Buenos_Aires"
    OPTION_71 = "America/Halifax"
    OPTION_72 = "America/Sao_Paulo"
    OPTION_73 = "Atlantic/Bermuda"
    OPTION_74 = "America/Caracas"
    OPTION_75 = "America/Indiana/Indianapolis"
    OPTION_76 = "America/New_York"
    OPTION_77 = "America/Puerto_Rico"
    OPTION_78 = "America/Santiago"
    OPTION_79 = "America/Bogota"
    OPTION_80 = "America/Chicago"
    OPTION_81 = "America/Lima"
    OPTION_82 = "America/Panama"
    OPTION_83 = "America/Denver"
    OPTION_84 = "America/El_Salvador"
    OPTION_85 = "America/Mexico_City"
    OPTION_86 = "America/Los_Angeles"
    OPTION_87 = "America/Mazatlan"
    OPTION_88 = "America/Phoenix"
    OPTION_89 = "America/Tijuana"
    OPTION_90 = "America/Anchorage"
    OPTION_91 = "Pacific/Pitcairn"
    OPTION_92 = "America/Adak"
    OPTION_93 = "Pacific/Gambier"
    OPTION_94 = "Pacific/Marquesas"
    OPTION_95 = "Pacific/Honolulu"
    OPTION_96 = "Pacific/Niue"
    OPTION_97 = "Pacific/Pago_Pago"


class LocaleSidKeyEnum(str, Enum):
    """Locale."""

    OPTION_0 = "af"
    OPTION_1 = "af_ZA"
    OPTION_2 = "sq"
    OPTION_3 = "sq_AL"
    OPTION_4 = "am"
    OPTION_5 = "am_ET"
    OPTION_6 = "ar"
    OPTION_7 = "ar_DZ"
    OPTION_8 = "ar_BH"
    OPTION_9 = "ar_EG"
    OPTION_10 = "ar_IQ"
    OPTION_11 = "ar_JO"
    OPTION_12 = "ar_KW"
    OPTION_13 = "ar_LB"
    OPTION_14 = "ar_LY"
    OPTION_15 = "ar_MA"
    OPTION_16 = "ar_OM"
    OPTION_17 = "ar_QA"
    OPTION_18 = "ar_SA"
    OPTION_19 = "ar_TN"
    OPTION_20 = "ar_AE"
    OPTION_21 = "ar_YE"
    OPTION_22 = "hy"
    OPTION_23 = "hy_AM"
    OPTION_24 = "az_AZ"
    OPTION_25 = "bn"
    OPTION_26 = "bn_BD"
    OPTION_27 = "bn_IN"
    OPTION_28 = "eu"
    OPTION_29 = "eu_ES"
    OPTION_30 = "be_BY"
    OPTION_31 = "bs"
    OPTION_32 = "bs_BA"
    OPTION_33 = "bg"
    OPTION_34 = "bg_BG"
    OPTION_35 = "my"
    OPTION_36 = "my_MM"
    OPTION_37 = "ca"
    OPTION_38 = "ca_ES_EURO"
    OPTION_39 = "ca_ES"
    OPTION_40 = "zh"
    OPTION_41 = "zh_CN_PINYIN"
    OPTION_42 = "zh_CN_STROKE"
    OPTION_43 = "zh_CN"
    OPTION_44 = "zh_HK_STROKE"
    OPTION_45 = "zh_HK"
    OPTION_46 = "zh_MO"
    OPTION_47 = "zh_SG"
    OPTION_48 = "zh_TW_STROKE"
    OPTION_49 = "zh_TW"
    OPTION_50 = "hr"
    OPTION_51 = "hr_HR"
    OPTION_52 = "cs"
    OPTION_53 = "cs_CZ"
    OPTION_54 = "da"
    OPTION_55 = "da_DK"
    OPTION_56 = "nl"
    OPTION_57 = "nl_AW"
    OPTION_58 = "nl_BE"
    OPTION_59 = "nl_NL"
    OPTION_60 = "nl_SR"
    OPTION_61 = "dz_BT"
    OPTION_62 = "en_AG"
    OPTION_63 = "en_AU"
    OPTION_64 = "en_BS"
    OPTION_65 = "en_BB"
    OPTION_66 = "en_BZ"
    OPTION_67 = "en_BM"
    OPTION_68 = "en_BW"
    OPTION_69 = "en_CM"
    OPTION_70 = "en_CA"
    OPTION_71 = "en_KY"
    OPTION_72 = "en_ER"
    OPTION_73 = "en_SZ"
    OPTION_74 = "en_FK"
    OPTION_75 = "en_FJ"
    OPTION_76 = "en_GM"
    OPTION_77 = "en_GH"
    OPTION_78 = "en_GI"
    OPTION_79 = "en_GY"
    OPTION_80 = "en_HK"
    OPTION_81 = "en_IN"
    OPTION_82 = "en_ID"
    OPTION_83 = "en_IE_EURO"
    OPTION_84 = "en_IE"
    OPTION_85 = "en_JM"
    OPTION_86 = "en_KE"
    OPTION_87 = "en_LR"
    OPTION_88 = "en_MG"
    OPTION_89 = "en_MW"
    OPTION_90 = "en_MY"
    OPTION_91 = "en_MU"
    OPTION_92 = "en_NA"
    OPTION_93 = "en_NZ"
    OPTION_94 = "en_NG"
    OPTION_95 = "en_PK"
    OPTION_96 = "en_PG"
    OPTION_97 = "en_PH"
    OPTION_98 = "en_RW"
    OPTION_99 = "en_WS"
    OPTION_100 = "en_SC"
    OPTION_101 = "en_SL"
    OPTION_102 = "en_SG"
    OPTION_103 = "en_SX"
    OPTION_104 = "en_SB"
    OPTION_105 = "en_ZA"
    OPTION_106 = "en_SH"
    OPTION_107 = "en_TZ"
    OPTION_108 = "en_TO"
    OPTION_109 = "en_TT"
    OPTION_110 = "en_UG"
    OPTION_111 = "en_GB"
    OPTION_112 = "en_US"
    OPTION_113 = "en_VU"
    OPTION_114 = "et"
    OPTION_115 = "et_EE"
    OPTION_116 = "fi"
    OPTION_117 = "fi_FI_EURO"
    OPTION_118 = "fi_FI"
    OPTION_119 = "fr"
    OPTION_120 = "fr_BE"
    OPTION_121 = "fr_CA"
    OPTION_122 = "fr_KM"
    OPTION_123 = "fr_FR_EURO"
    OPTION_124 = "fr_FR"
    OPTION_125 = "fr_GN"
    OPTION_126 = "fr_HT"
    OPTION_127 = "fr_LU"
    OPTION_128 = "fr_MR"
    OPTION_129 = "fr_MC"
    OPTION_130 = "fr_CH"
    OPTION_131 = "fr_WF"
    OPTION_132 = "ka"
    OPTION_133 = "ka_GE"
    OPTION_134 = "de"
    OPTION_135 = "de_AT_EURO"
    OPTION_136 = "de_AT"
    OPTION_137 = "de_BE"
    OPTION_138 = "de_DE_EURO"
    OPTION_139 = "de_DE"
    OPTION_140 = "de_LU_EURO"
    OPTION_141 = "de_LU"
    OPTION_142 = "de_CH"
    OPTION_143 = "el"
    OPTION_144 = "el_GR"
    OPTION_145 = "gu"
    OPTION_146 = "gu_IN"
    OPTION_147 = "iw"
    OPTION_148 = "iw_IL"
    OPTION_149 = "hi"
    OPTION_150 = "hi_IN"
    OPTION_151 = "hu"
    OPTION_152 = "hu_HU"
    OPTION_153 = "is"
    OPTION_154 = "is_IS"
    OPTION_155 = "in"
    OPTION_156 = "in_ID"
    OPTION_157 = "ga"
    OPTION_158 = "ga_IE"
    OPTION_159 = "it"
    OPTION_160 = "it_IT"
    OPTION_161 = "it_CH"
    OPTION_162 = "ja"
    OPTION_163 = "ja_JP"
    OPTION_164 = "kn"
    OPTION_165 = "kn_IN"
    OPTION_166 = "kk_KZ"
    OPTION_167 = "km"
    OPTION_168 = "km_KH"
    OPTION_169 = "ko"
    OPTION_170 = "ko_KR"
    OPTION_171 = "ky_KG"
    OPTION_172 = "lo_LA"
    OPTION_173 = "lv"
    OPTION_174 = "lv_LV"
    OPTION_175 = "lt"
    OPTION_176 = "lt_LT"
    OPTION_177 = "lu_CD"
    OPTION_178 = "lb"
    OPTION_179 = "lb_LU"
    OPTION_180 = "mk"
    OPTION_181 = "mk_MK"
    OPTION_182 = "ms"
    OPTION_183 = "ms_BN"
    OPTION_184 = "ms_MY"
    OPTION_185 = "ml"
    OPTION_186 = "ml_IN"
    OPTION_187 = "mt"
    OPTION_188 = "mt_MT"
    OPTION_189 = "mr"
    OPTION_190 = "mr_IN"
    OPTION_191 = "sh_ME_USD"
    OPTION_192 = "sh_ME"
    OPTION_193 = "ne_NP"
    OPTION_194 = "no"
    OPTION_195 = "no_NO"
    OPTION_196 = "ps_AF"
    OPTION_197 = "fa"
    OPTION_198 = "pl"
    OPTION_199 = "pl_PL"
    OPTION_200 = "pt"
    OPTION_201 = "pt_AO"
    OPTION_202 = "pt_BR"
    OPTION_203 = "pt_CV"
    OPTION_204 = "pt_MZ"
    OPTION_205 = "pt_PT"
    OPTION_206 = "pt_ST"
    OPTION_207 = "ro"
    OPTION_208 = "ro_MD"
    OPTION_209 = "ro_RO"
    OPTION_210 = "rm"
    OPTION_211 = "rm_CH"
    OPTION_212 = "rn_BI"
    OPTION_213 = "ru"
    OPTION_214 = "ru_KZ"
    OPTION_215 = "ru_RU"
    OPTION_216 = "sr"
    OPTION_217 = "sr_BA"
    OPTION_218 = "sr_CS"
    OPTION_219 = "sh"
    OPTION_220 = "sh_BA"
    OPTION_221 = "sh_CS"
    OPTION_222 = "sr_RS"
    OPTION_223 = "sk"
    OPTION_224 = "sk_SK"
    OPTION_225 = "sl"
    OPTION_226 = "sl_SI"
    OPTION_227 = "so_DJ"
    OPTION_228 = "so_SO"
    OPTION_229 = "es"
    OPTION_230 = "es_AR"
    OPTION_231 = "es_BO"
    OPTION_232 = "es_CL"
    OPTION_233 = "es_CO"
    OPTION_234 = "es_CR"
    OPTION_235 = "es_DO"
    OPTION_236 = "es_EC"
    OPTION_237 = "es_SV"
    OPTION_238 = "es_GT"
    OPTION_239 = "es_HN"
    OPTION_240 = "es_MX"
    OPTION_241 = "es_NI"
    OPTION_242 = "es_PA"
    OPTION_243 = "es_PY"
    OPTION_244 = "es_PE"
    OPTION_245 = "es_PR"
    OPTION_246 = "es_ES_EURO"
    OPTION_247 = "es_ES"
    OPTION_248 = "es_US"
    OPTION_249 = "es_UY"
    OPTION_250 = "es_VE"
    OPTION_251 = "sw"
    OPTION_252 = "sw_KE"
    OPTION_253 = "sv"
    OPTION_254 = "sv_SE"
    OPTION_255 = "tl"
    OPTION_256 = "tl_PH"
    OPTION_257 = "tg_TJ"
    OPTION_258 = "ta"
    OPTION_259 = "ta_IN"
    OPTION_260 = "ta_LK"
    OPTION_261 = "te"
    OPTION_262 = "te_IN"
    OPTION_263 = "mi"
    OPTION_264 = "mi_NZ"
    OPTION_265 = "th"
    OPTION_266 = "th_TH"
    OPTION_267 = "ti_ET"
    OPTION_268 = "tr"
    OPTION_269 = "tr_TR"
    OPTION_270 = "uk"
    OPTION_271 = "uk_UA"
    OPTION_272 = "ur"
    OPTION_273 = "ur_PK"
    OPTION_274 = "uz_LATN_UZ"
    OPTION_275 = "vi"
    OPTION_276 = "vi_VN"
    OPTION_277 = "cy"
    OPTION_278 = "cy_GB"
    OPTION_279 = "xh"
    OPTION_280 = "xh_ZA"
    OPTION_281 = "yo_BJ"
    OPTION_282 = "zu"
    OPTION_283 = "zu_ZA"


class EmailEncodingKeyEnum(str, Enum):
    """Email Encoding."""

    OPTION_0 = "UTF-8"
    OPTION_1 = "ISO-8859-1"
    OPTION_2 = "Shift_JIS"
    OPTION_3 = "ISO-2022-JP"
    OPTION_4 = "EUC-JP"
    OPTION_5 = "ks_c_5601-1987"
    OPTION_6 = "Big5"
    OPTION_7 = "GB2312"
    OPTION_8 = "Big5-HKSCS"
    OPTION_9 = "x-SJIS_0213"


class DefaultCurrencyIsoCodeEnum(str, Enum):
    """Default Currency ISO Code."""

    OPTION_0 = "AUD"
    OPTION_1 = "GBP"
    OPTION_2 = "CAD"
    OPTION_3 = "EUR"
    OPTION_4 = "INR"
    OPTION_5 = "JPY"
    OPTION_6 = "SGD"
    OPTION_7 = "SEK"
    OPTION_8 = "USD"


class CurrencyIsoCodeEnum(str, Enum):
    """Currency ISO Code."""

    OPTION_0 = "AUD"
    OPTION_1 = "GBP"
    OPTION_2 = "CAD"
    OPTION_3 = "EUR"
    OPTION_4 = "INR"
    OPTION_5 = "JPY"
    OPTION_6 = "SGD"
    OPTION_7 = "SEK"
    OPTION_8 = "USD"


class UserTypeEnum(str, Enum):
    """User Type."""

    OPTION_0 = "Standard"
    OPTION_1 = "PowerPartner"
    OPTION_2 = "PowerCustomerSuccess"
    OPTION_3 = "CustomerSuccess"
    OPTION_4 = "Guest"
    OPTION_5 = "CspLitePortal"
    OPTION_6 = "CsnOnly"
    OPTION_7 = "SelfService"


class LanguageLocaleKeyEnum(str, Enum):
    """Language."""

    OPTION_0 = "en_US"
    OPTION_1 = "de"
    OPTION_2 = "es"
    OPTION_3 = "fr"
    OPTION_4 = "it"
    OPTION_5 = "ja"
    OPTION_6 = "sv"
    OPTION_7 = "ko"
    OPTION_8 = "zh_TW"
    OPTION_9 = "zh_CN"
    OPTION_10 = "pt_BR"
    OPTION_11 = "nl_NL"
    OPTION_12 = "da"
    OPTION_13 = "th"
    OPTION_14 = "fi"
    OPTION_15 = "ru"
    OPTION_16 = "es_MX"
    OPTION_17 = "no"
    OPTION_18 = "hu"
    OPTION_19 = "pl"
    OPTION_20 = "cs"
    OPTION_21 = "tr"
    OPTION_22 = "in"
    OPTION_23 = "ro"
    OPTION_24 = "vi"
    OPTION_25 = "uk"
    OPTION_26 = "iw"
    OPTION_27 = "el"
    OPTION_28 = "bg"
    OPTION_29 = "en_GB"
    OPTION_30 = "ar"
    OPTION_31 = "sk"
    OPTION_32 = "pt_PT"
    OPTION_33 = "hr"
    OPTION_34 = "sl"


class DigestFrequencyEnum(str, Enum):
    """Chatter Email Highlights Frequency."""

    OPTION_0 = "D"
    OPTION_1 = "W"
    OPTION_2 = "N"


class DefaultGroupNotificationFrequencyEnum(str, Enum):
    """Default Notification Frequency when Joining Groups."""

    OPTION_0 = "P"
    OPTION_1 = "D"
    OPTION_2 = "W"
    OPTION_3 = "N"


class SlaWarningNotificationLevelEnum(str, Enum):
    """SLA Warning Notification Level."""

    OPTION_0 = "Email"
    OPTION_1 = "None"


class ManagementLevelEnum(str, Enum):
    """Management Level."""

    OPTION_0 = "Executive"
    OPTION_1 = "Management"
    OPTION_2 = "Technical"
    OPTION_3 = "Professional"
    OPTION_4 = "Support"


class User(SObjectBase, metaclass=SObjectType):
    """User."""

    _can_be_approved = True
    _base_sf_object = "User"

    model_config = ConfigDict(
        title="User",
        validate_assignment=True,
    )

    id_: str = Field(..., alias="Id", title="User ID", frozen=True, exclude=True)
    username: str = Field(..., alias="Username", title="Username")
    last_name: str = Field(..., alias="LastName", title="Last Name")
    first_name: Optional[str] = Field(..., alias="FirstName", title="First Name")
    name: str = Field(..., alias="Name", title="Full Name", frozen=True, exclude=True)
    company_name: Optional[str] = Field(..., alias="CompanyName", title="Company Name")
    division: Optional[str] = Field(..., alias="Division", title="Division")
    department: Optional[str] = Field(..., alias="Department", title="Department")
    title: Optional[str] = Field(..., alias="Title", title="Title")
    street: Optional[str] = Field(..., alias="Street", title="Street")
    city: Optional[str] = Field(..., alias="City", title="City")
    state: Optional[str] = Field(..., alias="State", title="State/Province")
    postal_code: Optional[str] = Field(..., alias="PostalCode", title="Zip/Postal Code")
    country: Optional[str] = Field(..., alias="Country", title="Country")
    latitude: Optional[float] = Field(..., alias="Latitude", title="Latitude")
    longitude: Optional[float] = Field(..., alias="Longitude", title="Longitude")
    geocode_accuracy: Optional[GeocodeAccuracyEnum] = Field(
        ..., alias="GeocodeAccuracy", title="Geocode Accuracy"
    )
    email: str = Field(..., alias="Email", title="Email")
    email_preferences_auto_bcc: bool = Field(
        ..., alias="EmailPreferencesAutoBcc", title="AutoBcc"
    )
    email_preferences_auto_bcc_stay_in_touch: bool = Field(
        ..., alias="EmailPreferencesAutoBccStayInTouch", title="AutoBccStayInTouch"
    )
    email_preferences_stay_in_touch_reminder: bool = Field(
        ..., alias="EmailPreferencesStayInTouchReminder", title="StayInTouchReminder"
    )
    sender_email: Optional[str] = Field(
        ..., alias="SenderEmail", title="Email Sender Address"
    )
    sender_name: Optional[str] = Field(
        ..., alias="SenderName", title="Email Sender Name"
    )
    signature: Optional[str] = Field(..., alias="Signature", title="Email Signature")
    stay_in_touch_subject: Optional[str] = Field(
        ..., alias="StayInTouchSubject", title="Stay-in-Touch Email Subject"
    )
    stay_in_touch_signature: Optional[str] = Field(
        ..., alias="StayInTouchSignature", title="Stay-in-Touch Email Signature"
    )
    stay_in_touch_note: Optional[str] = Field(
        ..., alias="StayInTouchNote", title="Stay-in-Touch Email Note"
    )
    phone: Optional[str] = Field(..., alias="Phone", title="Phone")
    fax: Optional[str] = Field(..., alias="Fax", title="Fax")
    mobile_phone: Optional[str] = Field(..., alias="MobilePhone", title="Mobile")
    alias: str = Field(..., alias="Alias", title="Alias")
    community_nickname: str = Field(..., alias="CommunityNickname", title="Nickname")
    badge_text: Optional[str] = Field(
        ...,
        alias="BadgeText",
        title="User Photo badge text overlay",
        frozen=True,
        exclude=True,
    )
    is_active: bool = Field(..., alias="IsActive", title="Active")
    time_zone_sid_key: TimeZoneSidKeyEnum = Field(
        ..., alias="TimeZoneSidKey", title="Time Zone"
    )
    user_role_id: Optional[str] = Field(..., alias="UserRoleId", title="Role ID")
    locale_sid_key: LocaleSidKeyEnum = Field(..., alias="LocaleSidKey", title="Locale")
    receives_info_emails: bool = Field(
        ..., alias="ReceivesInfoEmails", title="Info Emails"
    )
    receives_admin_info_emails: bool = Field(
        ..., alias="ReceivesAdminInfoEmails", title="Admin Info Emails"
    )
    email_encoding_key: EmailEncodingKeyEnum = Field(
        ..., alias="EmailEncodingKey", title="Email Encoding"
    )
    default_currency_iso_code: Optional[DefaultCurrencyIsoCodeEnum] = Field(
        ..., alias="DefaultCurrencyIsoCode", title="Default Currency ISO Code"
    )
    currency_iso_code: CurrencyIsoCodeEnum = Field(
        ..., alias="CurrencyIsoCode", title="Currency ISO Code"
    )
    profile_id: str = Field(
        ..., alias="ProfileId", title="Profile ID", frozen=True, exclude=True
    )
    user_type: Optional[UserTypeEnum] = Field(
        ..., alias="UserType", title="User Type", frozen=True, exclude=True
    )
    language_locale_key: LanguageLocaleKeyEnum = Field(
        ..., alias="LanguageLocaleKey", title="Language"
    )
    employee_number: Optional[str] = Field(
        ..., alias="EmployeeNumber", title="Employee Number"
    )
    delegated_approver_id: Optional[str] = Field(
        ..., alias="DelegatedApproverId", title="Delegated Approver ID"
    )
    manager_id: Optional[str] = Field(
        ..., alias="ManagerId", title="Manager ID", frozen=True, exclude=True
    )
    last_login_date: Optional[datetime] = Field(
        ..., alias="LastLoginDate", title="Last Login", frozen=True, exclude=True
    )
    created_date: datetime = Field(
        ..., alias="CreatedDate", title="Created Date", frozen=True, exclude=True
    )
    created_by_id: str = Field(
        ..., alias="CreatedById", title="Created By ID", frozen=True, exclude=True
    )
    last_modified_date: datetime = Field(
        ...,
        alias="LastModifiedDate",
        title="Last Modified Date",
        frozen=True,
        exclude=True,
    )
    last_modified_by_id: str = Field(
        ...,
        alias="LastModifiedById",
        title="Last Modified By ID",
        frozen=True,
        exclude=True,
    )
    system_modstamp: datetime = Field(
        ..., alias="SystemModstamp", title="System Modstamp", frozen=True, exclude=True
    )
    offline_trial_expiration_date: Optional[datetime] = Field(
        ...,
        alias="OfflineTrialExpirationDate",
        title="Offline Edition Trial Expiration Date",
        frozen=True,
        exclude=True,
    )
    offline_pda_trial_expiration_date: Optional[datetime] = Field(
        ...,
        alias="OfflinePdaTrialExpirationDate",
        title="Sales Anywhere Trial Expiration Date",
        frozen=True,
        exclude=True,
    )
    user_permissions_marketing_user: bool = Field(
        ...,
        alias="UserPermissionsMarketingUser",
        title="Marketing User",
        frozen=True,
        exclude=True,
    )
    user_permissions_offline_user: bool = Field(
        ...,
        alias="UserPermissionsOfflineUser",
        title="Offline User",
        frozen=True,
        exclude=True,
    )
    user_permissions_call_center_auto_login: bool = Field(
        ...,
        alias="UserPermissionsCallCenterAutoLogin",
        title="Auto-login To Call Center",
    )
    user_permissions_sf_content_user: bool = Field(
        ...,
        alias="UserPermissionsSFContentUser",
        title="Salesforce CRM Content User",
        frozen=True,
        exclude=True,
    )
    user_permissions_knowledge_user: bool = Field(
        ...,
        alias="UserPermissionsKnowledgeUser",
        title="Knowledge User",
        frozen=True,
        exclude=True,
    )
    user_permissions_interaction_user: bool = Field(
        ...,
        alias="UserPermissionsInteractionUser",
        title="Flow User",
        frozen=True,
        exclude=True,
    )
    user_permissions_support_user: bool = Field(
        ...,
        alias="UserPermissionsSupportUser",
        title="Service Cloud User",
        frozen=True,
        exclude=True,
    )
    user_permissions_chatter_answers_user: bool = Field(
        ...,
        alias="UserPermissionsChatterAnswersUser",
        title="Chatter Answers User",
        frozen=True,
        exclude=True,
    )
    user_permissions_work_dot_com_user_feature: bool = Field(
        ...,
        alias="UserPermissionsWorkDotComUserFeature",
        title="WDC User",
        frozen=True,
        exclude=True,
    )
    forecast_enabled: bool = Field(
        ..., alias="ForecastEnabled", title="Allow Forecasting"
    )
    user_preferences_activity_reminders_popup: bool = Field(
        ...,
        alias="UserPreferencesActivityRemindersPopup",
        title="ActivityRemindersPopup",
    )
    user_preferences_event_reminders_checkbox_default: bool = Field(
        ...,
        alias="UserPreferencesEventRemindersCheckboxDefault",
        title="EventRemindersCheckboxDefault",
    )
    user_preferences_task_reminders_checkbox_default: bool = Field(
        ...,
        alias="UserPreferencesTaskRemindersCheckboxDefault",
        title="TaskRemindersCheckboxDefault",
    )
    user_preferences_reminder_sound_off: bool = Field(
        ..., alias="UserPreferencesReminderSoundOff", title="ReminderSoundOff"
    )
    user_preferences_disable_all_feeds_email: bool = Field(
        ..., alias="UserPreferencesDisableAllFeedsEmail", title="DisableAllFeedsEmail"
    )
    user_preferences_disable_followers_email: bool = Field(
        ..., alias="UserPreferencesDisableFollowersEmail", title="DisableFollowersEmail"
    )
    user_preferences_disable_profile_post_email: bool = Field(
        ...,
        alias="UserPreferencesDisableProfilePostEmail",
        title="DisableProfilePostEmail",
    )
    user_preferences_disable_change_comment_email: bool = Field(
        ...,
        alias="UserPreferencesDisableChangeCommentEmail",
        title="DisableChangeCommentEmail",
    )
    user_preferences_disable_later_comment_email: bool = Field(
        ...,
        alias="UserPreferencesDisableLaterCommentEmail",
        title="DisableLaterCommentEmail",
    )
    user_preferences_dis_prof_post_comment_email: bool = Field(
        ...,
        alias="UserPreferencesDisProfPostCommentEmail",
        title="DisProfPostCommentEmail",
    )
    user_preferences_content_no_email: bool = Field(
        ..., alias="UserPreferencesContentNoEmail", title="ContentNoEmail"
    )
    user_preferences_content_email_as_and_when: bool = Field(
        ..., alias="UserPreferencesContentEmailAsAndWhen", title="ContentEmailAsAndWhen"
    )
    user_preferences_apex_pages_developer_mode: bool = Field(
        ...,
        alias="UserPreferencesApexPagesDeveloperMode",
        title="ApexPagesDeveloperMode",
    )
    user_preferences_receive_no_notifications_as_approver: bool = Field(
        ...,
        alias="UserPreferencesReceiveNoNotificationsAsApprover",
        title="ReceiveNoNotificationsAsApprover",
    )
    user_preferences_receive_notifications_as_delegated_approver: bool = Field(
        ...,
        alias="UserPreferencesReceiveNotificationsAsDelegatedApprover",
        title="ReceiveNotificationsAsDelegatedApprover",
    )
    user_preferences_hide_csn_get_chatter_mobile_task: bool = Field(
        ...,
        alias="UserPreferencesHideCSNGetChatterMobileTask",
        title="HideCSNGetChatterMobileTask",
    )
    user_preferences_disable_mentions_post_email: bool = Field(
        ...,
        alias="UserPreferencesDisableMentionsPostEmail",
        title="DisableMentionsPostEmail",
    )
    user_preferences_dis_mentions_comment_email: bool = Field(
        ...,
        alias="UserPreferencesDisMentionsCommentEmail",
        title="DisMentionsCommentEmail",
    )
    user_preferences_hide_csn_desktop_task: bool = Field(
        ..., alias="UserPreferencesHideCSNDesktopTask", title="HideCSNDesktopTask"
    )
    user_preferences_hide_chatter_onboarding_splash: bool = Field(
        ...,
        alias="UserPreferencesHideChatterOnboardingSplash",
        title="HideChatterOnboardingSplash",
    )
    user_preferences_hide_second_chatter_onboarding_splash: bool = Field(
        ...,
        alias="UserPreferencesHideSecondChatterOnboardingSplash",
        title="HideSecondChatterOnboardingSplash",
    )
    user_preferences_dis_comment_after_like_email: bool = Field(
        ...,
        alias="UserPreferencesDisCommentAfterLikeEmail",
        title="DisCommentAfterLikeEmail",
    )
    user_preferences_disable_like_email: bool = Field(
        ..., alias="UserPreferencesDisableLikeEmail", title="DisableLikeEmail"
    )
    user_preferences_sort_feed_by_comment: bool = Field(
        ..., alias="UserPreferencesSortFeedByComment", title="SortFeedByComment"
    )
    user_preferences_disable_message_email: bool = Field(
        ..., alias="UserPreferencesDisableMessageEmail", title="DisableMessageEmail"
    )
    user_preferences_disable_bookmark_email: bool = Field(
        ..., alias="UserPreferencesDisableBookmarkEmail", title="DisableBookmarkEmail"
    )
    user_preferences_disable_share_post_email: bool = Field(
        ..., alias="UserPreferencesDisableSharePostEmail", title="DisableSharePostEmail"
    )
    user_preferences_enable_auto_sub_for_feeds: bool = Field(
        ..., alias="UserPreferencesEnableAutoSubForFeeds", title="EnableAutoSubForFeeds"
    )
    user_preferences_disable_file_share_notifications_for_api: bool = Field(
        ...,
        alias="UserPreferencesDisableFileShareNotificationsForApi",
        title="DisableFileShareNotificationsForApi",
    )
    user_preferences_show_title_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowTitleToExternalUsers",
        title="ShowTitleToExternalUsers",
    )
    user_preferences_show_manager_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowManagerToExternalUsers",
        title="ShowManagerToExternalUsers",
    )
    user_preferences_show_email_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowEmailToExternalUsers",
        title="ShowEmailToExternalUsers",
    )
    user_preferences_show_work_phone_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowWorkPhoneToExternalUsers",
        title="ShowWorkPhoneToExternalUsers",
    )
    user_preferences_show_mobile_phone_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowMobilePhoneToExternalUsers",
        title="ShowMobilePhoneToExternalUsers",
    )
    user_preferences_show_fax_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowFaxToExternalUsers",
        title="ShowFaxToExternalUsers",
    )
    user_preferences_show_street_address_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowStreetAddressToExternalUsers",
        title="ShowStreetAddressToExternalUsers",
    )
    user_preferences_show_city_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowCityToExternalUsers",
        title="ShowCityToExternalUsers",
    )
    user_preferences_show_state_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowStateToExternalUsers",
        title="ShowStateToExternalUsers",
    )
    user_preferences_show_postal_code_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowPostalCodeToExternalUsers",
        title="ShowPostalCodeToExternalUsers",
    )
    user_preferences_show_country_to_external_users: bool = Field(
        ...,
        alias="UserPreferencesShowCountryToExternalUsers",
        title="ShowCountryToExternalUsers",
    )
    user_preferences_show_profile_pic_to_guest_users: bool = Field(
        ...,
        alias="UserPreferencesShowProfilePicToGuestUsers",
        title="ShowProfilePicToGuestUsers",
    )
    user_preferences_show_title_to_guest_users: bool = Field(
        ..., alias="UserPreferencesShowTitleToGuestUsers", title="ShowTitleToGuestUsers"
    )
    user_preferences_show_city_to_guest_users: bool = Field(
        ..., alias="UserPreferencesShowCityToGuestUsers", title="ShowCityToGuestUsers"
    )
    user_preferences_show_state_to_guest_users: bool = Field(
        ..., alias="UserPreferencesShowStateToGuestUsers", title="ShowStateToGuestUsers"
    )
    user_preferences_show_postal_code_to_guest_users: bool = Field(
        ...,
        alias="UserPreferencesShowPostalCodeToGuestUsers",
        title="ShowPostalCodeToGuestUsers",
    )
    user_preferences_show_country_to_guest_users: bool = Field(
        ...,
        alias="UserPreferencesShowCountryToGuestUsers",
        title="ShowCountryToGuestUsers",
    )
    user_preferences_hide_invoices_redirect_confirmation: bool = Field(
        ...,
        alias="UserPreferencesHideInvoicesRedirectConfirmation",
        title="HideInvoicesRedirectConfirmation",
    )
    user_preferences_hide_statements_redirect_confirmation: bool = Field(
        ...,
        alias="UserPreferencesHideStatementsRedirectConfirmation",
        title="HideStatementsRedirectConfirmation",
    )
    user_preferences_hide_s1_browser_ui: bool = Field(
        ..., alias="UserPreferencesHideS1BrowserUI", title="HideS1BrowserUI"
    )
    user_preferences_disable_endorsement_email: bool = Field(
        ...,
        alias="UserPreferencesDisableEndorsementEmail",
        title="DisableEndorsementEmail",
    )
    user_preferences_path_assistant_collapsed: bool = Field(
        ...,
        alias="UserPreferencesPathAssistantCollapsed",
        title="PathAssistantCollapsed",
    )
    user_preferences_cache_diagnostics: bool = Field(
        ..., alias="UserPreferencesCacheDiagnostics", title="CacheDiagnostics"
    )
    user_preferences_show_email_to_guest_users: bool = Field(
        ..., alias="UserPreferencesShowEmailToGuestUsers", title="ShowEmailToGuestUsers"
    )
    user_preferences_show_manager_to_guest_users: bool = Field(
        ...,
        alias="UserPreferencesShowManagerToGuestUsers",
        title="ShowManagerToGuestUsers",
    )
    user_preferences_show_work_phone_to_guest_users: bool = Field(
        ...,
        alias="UserPreferencesShowWorkPhoneToGuestUsers",
        title="ShowWorkPhoneToGuestUsers",
    )
    user_preferences_show_mobile_phone_to_guest_users: bool = Field(
        ...,
        alias="UserPreferencesShowMobilePhoneToGuestUsers",
        title="ShowMobilePhoneToGuestUsers",
    )
    user_preferences_show_fax_to_guest_users: bool = Field(
        ..., alias="UserPreferencesShowFaxToGuestUsers", title="ShowFaxToGuestUsers"
    )
    user_preferences_show_street_address_to_guest_users: bool = Field(
        ...,
        alias="UserPreferencesShowStreetAddressToGuestUsers",
        title="ShowStreetAddressToGuestUsers",
    )
    user_preferences_lightning_experience_preferred: bool = Field(
        ...,
        alias="UserPreferencesLightningExperiencePreferred",
        title="LightningExperiencePreferred",
    )
    user_preferences_hide_end_user_onboarding_assistant_modal: bool = Field(
        ...,
        alias="UserPreferencesHideEndUserOnboardingAssistantModal",
        title="HideEndUserOnboardingAssistantModal",
    )
    user_preferences_hide_lightning_migration_modal: bool = Field(
        ...,
        alias="UserPreferencesHideLightningMigrationModal",
        title="HideLightningMigrationModal",
    )
    user_preferences_hide_sfx_welcome_mat: bool = Field(
        ..., alias="UserPreferencesHideSfxWelcomeMat", title="HideSfxWelcomeMat"
    )
    user_preferences_hide_bigger_photo_callout: bool = Field(
        ...,
        alias="UserPreferencesHideBiggerPhotoCallout",
        title="HideBiggerPhotoCallout",
    )
    user_preferences_global_nav_bar_wt_shown: bool = Field(
        ..., alias="UserPreferencesGlobalNavBarWTShown", title="GlobalNavBarWTShown"
    )
    user_preferences_global_nav_grid_menu_wt_shown: bool = Field(
        ...,
        alias="UserPreferencesGlobalNavGridMenuWTShown",
        title="GlobalNavGridMenuWTShown",
    )
    user_preferences_create_lex_apps_wt_shown: bool = Field(
        ..., alias="UserPreferencesCreateLEXAppsWTShown", title="CreateLEXAppsWTShown"
    )
    user_preferences_favorites_wt_shown: bool = Field(
        ..., alias="UserPreferencesFavoritesWTShown", title="FavoritesWTShown"
    )
    user_preferences_record_home_section_collapse_wt_shown: bool = Field(
        ...,
        alias="UserPreferencesRecordHomeSectionCollapseWTShown",
        title="RecordHomeSectionCollapseWTShown",
    )
    user_preferences_record_home_reserved_wt_shown: bool = Field(
        ...,
        alias="UserPreferencesRecordHomeReservedWTShown",
        title="RecordHomeReservedWTShown",
    )
    user_preferences_favorites_show_top_favorites: bool = Field(
        ...,
        alias="UserPreferencesFavoritesShowTopFavorites",
        title="FavoritesShowTopFavorites",
    )
    user_preferences_exclude_mail_app_attachments: bool = Field(
        ...,
        alias="UserPreferencesExcludeMailAppAttachments",
        title="ExcludeMailAppAttachments",
    )
    user_preferences_suppress_task_sfx_reminders: bool = Field(
        ...,
        alias="UserPreferencesSuppressTaskSFXReminders",
        title="SuppressTaskSFXReminders",
    )
    user_preferences_suppress_event_sfx_reminders: bool = Field(
        ...,
        alias="UserPreferencesSuppressEventSFXReminders",
        title="SuppressEventSFXReminders",
    )
    user_preferences_preview_custom_theme: bool = Field(
        ..., alias="UserPreferencesPreviewCustomTheme", title="PreviewCustomTheme"
    )
    user_preferences_has_celebration_badge: bool = Field(
        ..., alias="UserPreferencesHasCelebrationBadge", title="HasCelebrationBadge"
    )
    user_preferences_user_debug_mode_pref: bool = Field(
        ..., alias="UserPreferencesUserDebugModePref", title="UserDebugModePref"
    )
    user_preferences_srh_override_activities: bool = Field(
        ..., alias="UserPreferencesSRHOverrideActivities", title="SRHOverrideActivities"
    )
    user_preferences_new_lightning_report_run_page_enabled: bool = Field(
        ...,
        alias="UserPreferencesNewLightningReportRunPageEnabled",
        title="NewLightningReportRunPageEnabled",
    )
    user_preferences_native_email_client: bool = Field(
        ..., alias="UserPreferencesNativeEmailClient", title="NativeEmailClient"
    )
    user_preferences_hide_browse_product_redirect_confirmation: bool = Field(
        ...,
        alias="UserPreferencesHideBrowseProductRedirectConfirmation",
        title="HideBrowseProductRedirectConfirmation",
    )
    contact_id: Optional[str] = Field(..., alias="ContactId", title="Contact ID")
    account_id: Optional[str] = Field(
        ..., alias="AccountId", title="Account ID", frozen=True, exclude=True
    )
    call_center_id: Optional[str] = Field(
        ..., alias="CallCenterId", title="Call Center ID"
    )
    extension: Optional[str] = Field(..., alias="Extension", title="Extension")
    federation_identifier: Optional[str] = Field(
        ...,
        alias="FederationIdentifier",
        title="SAML Federation ID",
        frozen=True,
        exclude=True,
    )
    about_me: Optional[str] = Field(..., alias="AboutMe", title="About Me")
    full_photo_url: Optional[str] = Field(
        ...,
        alias="FullPhotoUrl",
        title="Url for full-sized Photo",
        frozen=True,
        exclude=True,
    )
    small_photo_url: Optional[str] = Field(
        ..., alias="SmallPhotoUrl", title="Photo", frozen=True, exclude=True
    )
    is_ext_indicator_visible: bool = Field(
        ...,
        alias="IsExtIndicatorVisible",
        title="Show external indicator",
        frozen=True,
        exclude=True,
    )
    out_of_office_message: Optional[str] = Field(
        ...,
        alias="OutOfOfficeMessage",
        title="Out of office message",
        frozen=True,
        exclude=True,
    )
    medium_photo_url: Optional[str] = Field(
        ...,
        alias="MediumPhotoUrl",
        title="Url for medium profile photo",
        frozen=True,
        exclude=True,
    )
    digest_frequency: DigestFrequencyEnum = Field(
        ..., alias="DigestFrequency", title="Chatter Email Highlights Frequency"
    )
    default_group_notification_frequency: DefaultGroupNotificationFrequencyEnum = Field(
        ...,
        alias="DefaultGroupNotificationFrequency",
        title="Default Notification Frequency when Joining Groups",
    )
    last_viewed_date: Optional[datetime] = Field(
        ..., alias="LastViewedDate", title="Last Viewed Date", frozen=True, exclude=True
    )
    last_referenced_date: Optional[datetime] = Field(
        ...,
        alias="LastReferencedDate",
        title="Last Referenced Date",
        frozen=True,
        exclude=True,
    )
    banner_photo_url: Optional[str] = Field(
        ...,
        alias="BannerPhotoUrl",
        title="Url for banner photo",
        frozen=True,
        exclude=True,
    )
    small_banner_photo_url: Optional[str] = Field(
        ...,
        alias="SmallBannerPhotoUrl",
        title="Url for IOS banner photo",
        frozen=True,
        exclude=True,
    )
    medium_banner_photo_url: Optional[str] = Field(
        ...,
        alias="MediumBannerPhotoUrl",
        title="Url for Android banner photo",
        frozen=True,
        exclude=True,
    )
    is_profile_photo_active: bool = Field(
        ...,
        alias="IsProfilePhotoActive",
        title="Has Profile Photo",
        frozen=True,
        exclude=True,
    )
    bugforce_email: Optional[str] = Field(
        ..., alias="Bugforce_Email__c", title="Bugforce Email"
    )
    external_id: Optional[str] = Field(..., alias="External_ID__c", title="External ID")
    show_all_work_comments: Optional[bool] = Field(
        ..., alias="Show_All_Work_Comments__c", title="Show All Work Comments"
    )
    team_member_allocation: Optional[str] = Field(
        ...,
        alias="Team_Member_Allocation__c",
        title="Team Member Allocation",
        frozen=True,
        exclude=True,
    )
    perforce_username: Optional[str] = Field(
        ..., alias="Perforce_Username__c", title="Perforce Username"
    )
    linked_in_email: Optional[str] = Field(
        ..., alias="LinkedIn_Email__c", title="LinkedIn Email"
    )
    my_future: Optional[str] = Field(..., alias="My_Future__c", title="My Future")
    summary: Optional[str] = Field(..., alias="Summary__c", title="Summary")
    sync_time_from_linkedin: Optional[datetime] = Field(
        ..., alias="Sync_Time_from_Linkedin__c", title="Sync Time from Linkedin"
    )
    awarded_points: Optional[float] = Field(
        ..., alias="AwardedPoints__c", title="Awarded Points", frozen=True, exclude=True
    )
    points: Optional[float] = Field(
        ..., alias="Points__c", title="Points", frozen=True, exclude=True
    )
    awarded_recognitions_this_week: Optional[float] = Field(
        ...,
        alias="AwardedRecognitionsThisWeek__c",
        title="Awarded Recognitions This Week",
    )
    business_unit: Optional[str] = Field(
        ..., alias="Business_Unit__c", title="Business Unit"
    )
    cost_center: Optional[str] = Field(..., alias="Cost_Center__c", title="Cost Center")
    notification_level: Optional[str] = Field(
        ..., alias="Notification_Level__c", title="Work Notification Level"
    )
    primary_coverage_country_pcc: Optional[str] = Field(
        ..., alias="Primary_Coverage_Country_PCC__c", title="Primary Coverage Country"
    )
    work_user_interface: Optional[str] = Field(
        ..., alias="Work_User_Interface__c", title="Work User Interface"
    )
    home_phone: Optional[str] = Field(..., alias="Home_Phone__c", title="Home Phone")
    personal_mobile_phone: Optional[str] = Field(
        ..., alias="Personal_Mobile_Phone__c", title="Personal Mobile Phone"
    )
    gus_user_type: Optional[str] = Field(
        ..., alias="GUS_User_Type__c", title="GUS User Type"
    )
    wall_preference: Optional[str] = Field(
        ..., alias="Wall_Preference__c", title="Wall Preference"
    )
    desk_location: Optional[str] = Field(
        ..., alias="Desk_Location__c", title="Desk Location", frozen=True, exclude=True
    )
    user_preference: Optional[str] = Field(
        ..., alias="User_Preference__c", title="User Preference"
    )
    certified_product_owner: Optional[bool] = Field(
        ..., alias="Certified_Product_Owner__c", title="Certified Product Owner"
    )
    certified_scrum_master: Optional[bool] = Field(
        ..., alias="Certified_Scrum_Master__c", title="Certified Scrum Lead"
    )
    product_owner_certified_date: Optional[date] = Field(
        ...,
        alias="Product_Owner_Certified_Date__c",
        title="Product Owner Certified Date",
    )
    scrum_master_certified_date: Optional[date] = Field(
        ..., alias="Scrum_Master_Certified_Date__c", title="Scrum Lead Certified Date"
    )
    oss_dashboard__git_hub_username: Optional[str] = Field(
        ..., alias="oss_dashboard__GitHub_Username__c", title="GitHub Username"
    )
    sla_warning_notification_level: Optional[SlaWarningNotificationLevelEnum] = Field(
        ...,
        alias="SLA_Warning_Notification_Level__c",
        title="SLA Warning Notification Level",
    )
    public_key: Optional[str] = Field(
        ..., alias="Public_Key__c", title="Public GPG/PGP Key"
    )
    profile_name: Optional[str] = Field(
        ..., alias="Profile_Name__c", title="Profile Name", frozen=True, exclude=True
    )
    roster_id: Optional[str] = Field(
        ..., alias="RosterId__c", title="Roster Id (H-ID) (Deprecated)"
    )
    kaiju_synthetic__kaiju_access_token_dev: Optional[str] = Field(
        ...,
        alias="kaiju_synthetic__Kaiju_Access_Token_Dev__c",
        title="Kaiju_Access_Token_Dev",
    )
    kaiju_synthetic__kaiju_access_token_sandbox: Optional[str] = Field(
        ...,
        alias="kaiju_synthetic__Kaiju_Access_Token_Sandbox__c",
        title="Kaiju_Access_Token_Sandbox",
    )
    kaiju_synthetic__kaiju_access_token: Optional[str] = Field(
        ..., alias="kaiju_synthetic__Kaiju_Access_Token__c", title="Kaiju_Access_Token"
    )
    kaiju_synthetic__kaiju_refresh_token_dev: Optional[str] = Field(
        ...,
        alias="kaiju_synthetic__Kaiju_Refresh_Token_Dev__c",
        title="Kaiju_Refresh_Token_Dev",
    )
    kaiju_synthetic__kaiju_refresh_token_sandbox: Optional[str] = Field(
        ...,
        alias="kaiju_synthetic__Kaiju_Refresh_Token_Sandbox__c",
        title="Kaiju_Refresh_Token_Sandbox",
    )
    kaiju_synthetic__kaiju_refresh_token: Optional[str] = Field(
        ...,
        alias="kaiju_synthetic__Kaiju_Refresh_Token__c",
        title="Kaiju_Refresh_Token",
    )
    kaiju_synthetic__kaiju_working_environment: Optional[str] = Field(
        ...,
        alias="kaiju_synthetic__Kaiju_Working_Environment__c",
        title="Kaiju_Working_Environment",
    )
    working_hours: Optional[str] = Field(
        ..., alias="Working_Hours__c", title="Working Hours"
    )
    employee_type: Optional[str] = Field(
        ..., alias="Employee_Type__c", title="Employee Type", frozen=True, exclude=True
    )
    slack_id: Optional[str] = Field(..., alias="Slack_Id__c", title="Slack Id")
    do_not_send_email_work_notification: Optional[bool] = Field(
        ...,
        alias="Do_Not_Send_Email_Work_Notification__c",
        title="Opt out of work notifications emails",
    )
    slack_work_notification: Optional[bool] = Field(
        ..., alias="Slack_Work_Notification__c", title="Send notifications to Slack"
    )
    phonetic_pronunciation: Optional[str] = Field(
        ..., alias="Phonetic_Pronunciation__c", title="Phonetic Spelling"
    )
    pronouns: Optional[str] = Field(..., alias="Pronouns__c", title="Pronouns")
    cloud_id: Optional[str] = Field(
        ..., alias="Cloud_ID__c", title="Cloud ID", frozen=True, exclude=True
    )
    cloud: Optional[str] = Field(
        ..., alias="Cloud__c", title="Cloud", frozen=True, exclude=True
    )
    parent_cloud_id: Optional[str] = Field(
        ...,
        alias="Parent_Cloud_ID__c",
        title="Parent Cloud ID",
        frozen=True,
        exclude=True,
    )
    parent_cloud: Optional[str] = Field(
        ..., alias="Parent_Cloud__c", title="Parent Cloud", frozen=True, exclude=True
    )
    workday_last_name: Optional[str] = Field(
        ...,
        alias="Workday_Last_Name__c",
        title="Workday Last Name",
        frozen=True,
        exclude=True,
    )
    workday_jobcode: Optional[str] = Field(
        ...,
        alias="Workday_Jobcode__c",
        title="Workday Jobcode",
        frozen=True,
        exclude=True,
    )
    workday_title: Optional[str] = Field(
        ..., alias="Workday_Title__c", title="Workday Title", frozen=True, exclude=True
    )
    workday_first_name: Optional[str] = Field(
        ...,
        alias="Workday_First_Name__c",
        title="Workday First Name",
        frozen=True,
        exclude=True,
    )
    workday_name: Optional[str] = Field(
        ..., alias="Workday_Name__c", title="Workday Name", frozen=True, exclude=True
    )
    initials: Optional[str] = Field(
        ..., alias="Initials__c", title="Initials", frozen=True, exclude=True
    )
    workday_worker_type: Optional[str] = Field(
        ...,
        alias="Workday_Worker_Type__c",
        title="Workday Worker Type",
        frozen=True,
        exclude=True,
    )
    workday_time_type: Optional[str] = Field(
        ...,
        alias="Workday_Time_Type__c",
        title="Workday Time Type",
        frozen=True,
        exclude=True,
    )
    workday_jobcode_old: Optional[str] = Field(
        ..., alias="Workday_Jobcode_old__c", title="Workday Jobcode Old"
    )
    is_manager: Optional[bool] = Field(
        ..., alias="Is_Manager__c", title="Is Manager", frozen=True, exclude=True
    )
    management_level: Optional[ManagementLevelEnum] = Field(
        ...,
        alias="Management_Level__c",
        title="Management Level",
        frozen=True,
        exclude=True,
    )
    kaiju_synthetic__kaiju_team: Optional[float] = Field(
        ..., alias="kaiju_synthetic__Kaiju_Team__c", title="Kaiju_Team"
    )
    resolve_perforce_username: Optional[str] = Field(
        ...,
        alias="Resolve_Perforce_Username__c",
        title="Resolve Perforce Username",
        frozen=True,
        exclude=True,
    )
    management_chain_01_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_01_Employee__c",
        title="Management Chain 01 Employee",
    )
    management_chain_02_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_02_Employee__c",
        title="Management Chain 02 Employee",
    )
    management_chain_03_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_03_Employee__c",
        title="Management Chain 03 Employee",
    )
    management_chain_04_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_04_Employee__c",
        title="Management Chain 04 Employee",
    )
    management_chain_05_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_05_Employee__c",
        title="Management Chain 05 Employee",
    )
    management_chain_06_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_06_Employee__c",
        title="Management Chain 06 Employee",
    )
    management_chain_07_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_07_Employee__c",
        title="Management Chain 07 Employee",
    )
    management_chain_08_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_08_Employee__c",
        title="Management Chain 08 Employee",
    )
    management_chain_09_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_09_Employee__c",
        title="Management Chain 09 Employee",
    )
    management_chain_10_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_10_Employee__c",
        title="Management Chain 10 Employee",
    )
    management_chain_11_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_11_Employee__c",
        title="Management Chain 11 Employee",
    )
    management_chain_12_employee: Optional[str] = Field(
        ...,
        alias="Management_Chain_12_Employee__c",
        title="Management Chain 12 Employee",
    )
    management_chain_level01_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level01_Employee_Number__c",
        title="Management Chain Level01 Employee Number",
    )
    management_chain_level02_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level02_Employee_Number__c",
        title="Management Chain Level02 Employee Number",
    )
    management_chain_level03_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level03_Employee_Number__c",
        title="Management Chain Level03 Employee Number",
    )
    management_chain_level04_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level04_Employee_Number__c",
        title="Management Chain Level04 Employee Number",
    )
    management_chain_level05_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level05_Employee_Number__c",
        title="Management Chain Level05 Employee Number",
    )
    management_chain_level06_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level06_Employee_Number__c",
        title="Management Chain Level06 Employee Number",
    )
    management_chain_level07_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level07_Employee_Number__c",
        title="Management Chain Level07 Employee Number",
    )
    management_chain_level08_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level08_Employee_Number__c",
        title="Management Chain Level08 Employee Number",
    )
    management_chain_level09_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level09_Employee_Number__c",
        title="Management Chain Level09 Employee Number",
    )
    management_chain_level10_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level10_Employee_Number__c",
        title="Management Chain Level10 Employee Number",
    )
    management_chain_level11_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level11_Employee_Number__c",
        title="Management Chain Level11 Employee Number",
    )
    management_chain_level12_employee_number: Optional[str] = Field(
        ...,
        alias="Management_Chain_Level12_Employee_Number__c",
        title="Management Chain Level12 Employee Number",
    )
    management_level_10_email: Optional[str] = Field(
        ...,
        alias="Management_Level_10_Email__c",
        title="Management Level 10 Email",
        frozen=True,
        exclude=True,
    )
    management_level_10_name: Optional[str] = Field(
        ...,
        alias="Management_Level_10_Name__c",
        title="Management Level 10 Name",
        frozen=True,
        exclude=True,
    )
    management_level_11_email: Optional[str] = Field(
        ...,
        alias="Management_Level_11_Email__c",
        title="Management Level 11 Email",
        frozen=True,
        exclude=True,
    )
    management_level_11_name: Optional[str] = Field(
        ...,
        alias="Management_Level_11_Name__c",
        title="Management Level 11 Name",
        frozen=True,
        exclude=True,
    )
    management_level_12_email: Optional[str] = Field(
        ...,
        alias="Management_Level_12_Email__c",
        title="Management Level 12 Email",
        frozen=True,
        exclude=True,
    )
    management_level_12_name: Optional[str] = Field(
        ...,
        alias="Management_Level_12_Name__c",
        title="Management Level 12 Name",
        frozen=True,
        exclude=True,
    )
    management_level_1_email: Optional[str] = Field(
        ...,
        alias="Management_Level_1_Email__c",
        title="Management Level 1 Email",
        frozen=True,
        exclude=True,
    )
    management_level_1_name: Optional[str] = Field(
        ...,
        alias="Management_Level_1_Name__c",
        title="Management Level 1 Name",
        frozen=True,
        exclude=True,
    )
    management_level_2_email: Optional[str] = Field(
        ...,
        alias="Management_Level_2_Email__c",
        title="Management Level 2 Email",
        frozen=True,
        exclude=True,
    )
    management_level_2_name: Optional[str] = Field(
        ...,
        alias="Management_Level_2_Name__c",
        title="Management Level 2 Name",
        frozen=True,
        exclude=True,
    )
    management_level_3_email: Optional[str] = Field(
        ...,
        alias="Management_Level_3_Email__c",
        title="Management Level 3 Email",
        frozen=True,
        exclude=True,
    )
    management_level_3_name: Optional[str] = Field(
        ...,
        alias="Management_Level_3_Name__c",
        title="Management Level 3 Name",
        frozen=True,
        exclude=True,
    )
    management_level_4_email: Optional[str] = Field(
        ...,
        alias="Management_Level_4_Email__c",
        title="Management Level 4 Email",
        frozen=True,
        exclude=True,
    )
    management_level_4_name: Optional[str] = Field(
        ...,
        alias="Management_Level_4_Name__c",
        title="Management Level 4 Name",
        frozen=True,
        exclude=True,
    )
    management_level_5_email: Optional[str] = Field(
        ...,
        alias="Management_Level_5_Email__c",
        title="Management Level 5 Email",
        frozen=True,
        exclude=True,
    )
    management_level_5_name: Optional[str] = Field(
        ...,
        alias="Management_Level_5_Name__c",
        title="Management Level 5 Name",
        frozen=True,
        exclude=True,
    )
    management_level_6_email: Optional[str] = Field(
        ...,
        alias="Management_Level_6_Email__c",
        title="Management Level 6 Email",
        frozen=True,
        exclude=True,
    )
    management_level_6_name: Optional[str] = Field(
        ...,
        alias="Management_Level_6_Name__c",
        title="Management Level 6 Name",
        frozen=True,
        exclude=True,
    )
    management_level_7_email: Optional[str] = Field(
        ...,
        alias="Management_Level_7_Email__c",
        title="Management Level 7 Email",
        frozen=True,
        exclude=True,
    )
    management_level_7_name: Optional[str] = Field(
        ...,
        alias="Management_Level_7_Name__c",
        title="Management Level 7 Name",
        frozen=True,
        exclude=True,
    )
    management_level_8_email: Optional[str] = Field(
        ...,
        alias="Management_Level_8_Email__c",
        title="Management Level 8 Email",
        frozen=True,
        exclude=True,
    )
    management_level_8_name: Optional[str] = Field(
        ...,
        alias="Management_Level_8_Name__c",
        title="Management Level 8 Name",
        frozen=True,
        exclude=True,
    )
    management_level_9_email: Optional[str] = Field(
        ...,
        alias="Management_Level_9_Email__c",
        title="Management Level 09 Email",
        frozen=True,
        exclude=True,
    )
    management_level_9_name: Optional[str] = Field(
        ...,
        alias="Management_Level_9_Name__c",
        title="Management Level 09 Name",
        frozen=True,
        exclude=True,
    )

    @property
    def user_role_name(self):
        return self._get_connected_object_name(["UserRole"], self.user_role_id)

    @property
    def profile_name(self):
        return self._get_connected_object_name(["Profile"], self.profile_id)

    @property
    def delegated_approver_name(self):
        return self._get_connected_object_name(
            ["Group", "User"], self.delegated_approver_id
        )

    @property
    def manager_name(self):
        return self._get_connected_object_name(["User"], self.manager_id)

    @property
    def created_by_name(self):
        return self._get_connected_object_name(["User"], self.created_by_id)

    @property
    def last_modified_by_name(self):
        return self._get_connected_object_name(["User"], self.last_modified_by_id)

    @property
    def contact_name(self):
        return self._get_connected_object_name(["Contact"], self.contact_id)

    @property
    def account_name(self):
        return self._get_connected_object_name(["Account"], self.account_id)

    @property
    def call_center_name(self):
        return self._get_connected_object_name(["CallCenter"], self.call_center_id)

    @property
    def management_chain_01_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_01_employee
        )

    @property
    def management_chain_02_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_02_employee
        )

    @property
    def management_chain_03_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_03_employee
        )

    @property
    def management_chain_04_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_04_employee
        )

    @property
    def management_chain_05_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_05_employee
        )

    @property
    def management_chain_06_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_06_employee
        )

    @property
    def management_chain_07_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_07_employee
        )

    @property
    def management_chain_08_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_08_employee
        )

    @property
    def management_chain_09_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_09_employee
        )

    @property
    def management_chain_10_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_10_employee
        )

    @property
    def management_chain_11_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_11_employee
        )

    @property
    def management_chain_12_employee_name(self):
        return self._get_connected_object_name(
            ["User"], self.management_chain_12_employee
        )

    def __init__(self, **kwargs: Any):
        """
        Initialize Salesforce Object.

        :param **kwargs: keyword arguments
        """
        super().__init__(**kwargs)

    @property
    def web_url(self) -> str:
        """
        Web URL.

        :returns: web url
        """
        return f"https://{GUSClient.instance().sf.sf_instance}/{self.id_}"

    @classmethod
    def get_by_id(cls, id_: str) -> Self:
        """
        Get user.

        :param id_: Salesforce Object Id
        :returns: User object
        """
        x = GUSClient.instance().sf.__getattr__("User").get(id_)
        return User(**{"sf": GUSClient.instance().sf, **x})

    @classmethod
    def create(cls, **kwargs: Any) -> Self:
        """
        Create user.
        :param **kwargs: values for the fields of the User object
        :returns: User object
        :raises RuntimeError: if object creation failed
        """
        lookup = cls._get_field_to_sf_name_dict()
        fields = {lookup[k]: v for k, v in kwargs.items()}
        return cls._create("FeedItem", fields)

    @classmethod
    def update(cls, model: Self, headers: Optional[Dict[str, str]] = None) -> None:
        """
        Update Salesforce API with changes.
        :param model: User object to update
        :param headers: headers to send with REST call
            https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers.htm
        """

        updates = model.model_dump_json(
            by_alias=True, exclude_unset=True, exclude_defaults=True, exclude_none=True
        )
        import json

        updates = json.loads(updates)  # TODO - better way to do this?
        if updates:
            GUSClient.instance().sf.__getattr__("User").update(
                model.id_, updates, headers=headers
            )

    @classmethod
    def soql_query(cls, where_clause: str) -> Generator[Self, None, None]:
        """
        Query Users by SOQL WHERE clause.

        :param where_clause: where clause of SOQL query
        :yields: User objects
        """
        for x in cls._query_soql("User", where_clause):
            yield User(**x)
